import {
  createSqliteDayPlanItem,
  createSqliteRecurringTaskInstance,
  getSqliteAppData,
  updateSqliteDayPlanItem,
  updateSqliteRecurringTaskInstance,
} from './sqlite.js'
import {
  addIntervalToDate,
  buildRecurringInstanceSearchKeys,
  matchesCalendarRepeatOnDate,
  parseDate,
  resolveRepeatRule,
  serializeRepeatRule,
  toDateString,
} from './repeat-rule.js'
import { resolveRecurringDeadlineDate } from './deadline.js'
import type {
  AppData,
  DayPlanItem,
  RecurringTaskInstance,
  RepeatRule,
  SceneTag,
  TaskTemplate,
  TimeBlock,
  TimeBlockSource,
} from './types.js'

type TimeContextResolution = {
  timeBlock: TimeBlock
  timeBlockSource: TimeBlockSource
}

type AutoGeneratedCandidate = {
  template: TaskTemplate
  recurringInstance: RecurringTaskInstance | null
  timeContext: TimeContextResolution
}

type RecurringGenerationResult = {
  appData: AppData
  recurringInstance: RecurringTaskInstance | null
  shouldGenerateDayPlanItem: boolean
}

const DAY_SCENE_NAMES = new Set(['上午', '下午', '白天'])
const NIGHT_SCENE_NAMES = new Set(['晚上', '夜间'])

const getRootItemId = (item: DayPlanItem) => item.rootItemId ?? item.id
const resolveOriginDate = (item: Pick<DayPlanItem, 'originDate' | 'targetDate' | 'date'>) =>
  item.originDate ?? item.targetDate ?? item.date

const compareItemsByDateDesc = (left: DayPlanItem, right: DayPlanItem) => {
  if (left.date !== right.date) {
    return right.date.localeCompare(left.date)
  }

  return right.createdAt.localeCompare(left.createdAt)
}

const getLatestItemsByRootBeforeDate = (items: DayPlanItem[], selectedDateKey: string) => {
  const latestByRoot = new Map<string, DayPlanItem>()

  items
    .filter((item) => item.date < selectedDateKey)
    .sort(compareItemsByDateDesc)
    .forEach((item) => {
      const rootItemId = getRootItemId(item)

      if (!latestByRoot.has(rootItemId)) {
        latestByRoot.set(rootItemId, item)
      }
    })

  return latestByRoot
}

const getRecurringInstanceMap = (appData: AppData) =>
  appData.recurringTaskInstances.reduce<Record<string, RecurringTaskInstance>>((map, instance) => {
    map[instance.id] = instance
    return map
  }, {})

const getTemplateKindMap = (appData: AppData) =>
  appData.taskTemplates.reduce<Record<string, TaskTemplate['templateKind']>>((map, template) => {
    map[template.id] = template.templateKind
    return map
  }, {})

const isRepeatingItem = (
  item: DayPlanItem,
  templateKindsById: Record<string, TaskTemplate['templateKind']>,
) => Boolean(item.recurringInstanceId || (item.templateId && templateKindsById[item.templateId] === 'todo_recurring'))

const isCarryableTodoItem = (
  item: DayPlanItem,
  selectedDateKey: string,
  templateKindsById: Record<string, TaskTemplate['templateKind']>,
  recurringInstancesById: Record<string, RecurringTaskInstance>,
) => {
  if (item.status !== 'pending') {
    return false
  }

  if (item.date >= selectedDateKey) {
    return false
  }

  if (isRepeatingItem(item, templateKindsById)) {
    if (!item.templateId) {
      return false
    }

    if (!item.recurringInstanceId) {
      return true
    }

    const recurringInstance = recurringInstancesById[item.recurringInstanceId]
    return Boolean(!recurringInstance || recurringInstance.status === 'pending')
  }

  if (item.isSegmented) {
    return item.progressPercent < 100
  }

  return true
}

const findLatestCarryableItemsByRoot = (
  appData: AppData,
  selectedDateKey: string,
  templateKindsById: Record<string, TaskTemplate['templateKind']>,
) => {
  const latestByRoot = new Map<string, DayPlanItem>()
  const latestItemsByRoot = getLatestItemsByRootBeforeDate(appData.dayPlanItems, selectedDateKey)
  const recurringInstancesById = getRecurringInstanceMap(appData)

  latestItemsByRoot.forEach((item, rootItemId) => {
    if (isCarryableTodoItem(item, selectedDateKey, templateKindsById, recurringInstancesById)) {
      latestByRoot.set(rootItemId, item)
    }
  })

  return latestByRoot
}

const hasRootItemOnDate = (items: DayPlanItem[], selectedDateKey: string, rootItemId: string) =>
  items.some((item) => item.date === selectedDateKey && getRootItemId(item) === rootItemId)

const resolveTimeContext = (sceneTagIds: string[], sceneTags: SceneTag[]): TimeContextResolution => {
  const sceneNames = sceneTags
    .filter((sceneTag) => sceneTagIds.includes(sceneTag.id))
    .map((sceneTag) => sceneTag.name)

  const hasNightTag = sceneNames.some((sceneName) => NIGHT_SCENE_NAMES.has(sceneName))

  if (hasNightTag) {
    return {
      timeBlock: 'night',
      timeBlockSource: 'mapped_night',
    }
  }

  const hasDayTag = sceneNames.some((sceneName) => DAY_SCENE_NAMES.has(sceneName))

  if (hasDayTag) {
    return {
      timeBlock: 'day',
      timeBlockSource: 'mapped_day',
    }
  }

  return {
    timeBlock: 'day',
    timeBlockSource: 'default_day',
  }
}

const hasConsumedTrigger = (appData: AppData, templateId: string, targetDate: string) =>
  appData.dayPlanItems.some(
    (item) =>
      item.templateId === templateId &&
      item.targetDate === targetDate &&
      item.consumesDateTrigger === true,
  )

const getLatestCompletedAtForTemplate = (appData: AppData, templateId: string) => {
  const completedAtCandidates = appData.recurringTaskInstances
    .filter((instance) => instance.templateId === templateId && instance.completedAt)
    .map((instance) => instance.completedAt as string)

  return completedAtCandidates.sort((left, right) => right.localeCompare(left))[0]
}

const findOpenPendingOccurrence = (appData: AppData, templateId: string) =>
  appData.dayPlanItems.find(
    (item) =>
      item.source === 'auto_generated' &&
      item.templateId === templateId &&
      item.status === 'pending',
  ) ?? null

const shouldGenerateCalendarOccurrence = (
  template: TaskTemplate,
  selectedDate: Date,
  selectedDateKey: string,
  repeatRule: RepeatRule,
) => {
  if (!template.date) {
    return false
  }

  if (repeatRule.repeatType === 'none') {
    return template.date === selectedDateKey
  }

  if (repeatRule.repeatType !== 'calendar' || !repeatRule.intervalUnit || !repeatRule.intervalValue) {
    return false
  }

  const templateDate = parseDate(template.date)

  if (selectedDate < templateDate) {
    return false
  }

  return (
    selectedDateKey === template.date ||
    matchesCalendarRepeatOnDate({
      anchorDate: templateDate,
      selectedDate,
      intervalUnit: repeatRule.intervalUnit,
      intervalValue: repeatRule.intervalValue,
    })
  )
}

const resolveAfterCompletionTargetDate = (
  appData: AppData,
  template: TaskTemplate,
  selectedDateKey: string,
  repeatRule: RepeatRule,
) => {
  if (repeatRule.repeatType !== 'afterCompletion' || !repeatRule.intervalUnit || !repeatRule.intervalValue) {
    return null
  }

  const openPendingOccurrence = findOpenPendingOccurrence(appData, template.id)

  if (openPendingOccurrence) {
    const pendingTargetDate =
      openPendingOccurrence.targetDate ?? openPendingOccurrence.originDate ?? openPendingOccurrence.date

    return pendingTargetDate === selectedDateKey ? pendingTargetDate : null
  }

  if (template.date === selectedDateKey && !hasConsumedTrigger(appData, template.id, selectedDateKey)) {
    return selectedDateKey
  }

  const latestCompletedAt = getLatestCompletedAtForTemplate(appData, template.id)

  if (!latestCompletedAt) {
    return null
  }

  const nextTargetDate = toDateString(
    addIntervalToDate(new Date(latestCompletedAt), repeatRule.intervalUnit, repeatRule.intervalValue),
  )

  if (nextTargetDate !== selectedDateKey) {
    return null
  }

  if (hasConsumedTrigger(appData, template.id, nextTargetDate)) {
    return null
  }

  return nextTargetDate
}

const ensureRecurringInstance = (
  appData: AppData,
  template: TaskTemplate,
  repeatRule: RepeatRule,
  targetDate: string,
  nowIso: string,
) => {
  const searchKeys = buildRecurringInstanceSearchKeys(parseDate(targetDate), repeatRule)
  const serializedRepeatRule = serializeRepeatRule(repeatRule)
  let recurringInstance =
    appData.recurringTaskInstances.find(
      (instance) =>
        instance.templateId === template.id &&
        (instance.targetDate === targetDate || searchKeys.includes(instance.dateKey)),
    ) ?? null
  let updatedRecurringInstances = appData.recurringTaskInstances

  if (!recurringInstance) {
    recurringInstance = {
      id: `recurring-instance-${template.id}-${targetDate}`,
      templateId: template.id,
      dateKey: targetDate,
      targetDate,
      recurrence:
        serializedRepeatRule.recurrence === 'none' ? 'daily' : serializedRepeatRule.recurrence,
      repeatType:
        serializedRepeatRule.repeatType === 'none' ? undefined : serializedRepeatRule.repeatType,
      repeatIntervalUnit: serializedRepeatRule.repeatIntervalUnit,
      repeatIntervalValue: serializedRepeatRule.repeatIntervalValue,
      status: 'pending',
      progressState: 'not_started',
      progressPercent: 0,
      progressNote: '',
      generatedAt: nowIso,
      updatedAt: nowIso,
    }

    updatedRecurringInstances = [...updatedRecurringInstances, recurringInstance]
  } else {
    const normalizedInstance = {
      ...recurringInstance,
      targetDate,
      recurrence:
        serializedRepeatRule.recurrence === 'none'
          ? recurringInstance.recurrence
          : serializedRepeatRule.recurrence,
      repeatType:
        serializedRepeatRule.repeatType === 'none'
          ? recurringInstance.repeatType
          : serializedRepeatRule.repeatType,
      repeatIntervalUnit: serializedRepeatRule.repeatIntervalUnit,
      repeatIntervalValue: serializedRepeatRule.repeatIntervalValue,
      updatedAt: recurringInstance.updatedAt,
    }

    updatedRecurringInstances = appData.recurringTaskInstances.map((instance) =>
      instance.id === recurringInstance!.id ? normalizedInstance : instance,
    )
    recurringInstance = normalizedInstance
  }

  return {
    appData: {
      ...appData,
      recurringTaskInstances: updatedRecurringInstances,
    },
    recurringInstance,
  }
}

const updateRecurringInstancesForTemplate = (
  appData: AppData,
  template: TaskTemplate,
  selectedDate: Date,
  selectedDateKey: string,
  nowIso: string,
): RecurringGenerationResult => {
  const repeatRule = resolveRepeatRule(template)

  if (repeatRule.repeatType === 'none') {
    return {
      appData,
      recurringInstance: null,
      shouldGenerateDayPlanItem: true,
    }
  }

  if (repeatRule.repeatType === 'calendar') {
    if (!shouldGenerateCalendarOccurrence(template, selectedDate, selectedDateKey, repeatRule)) {
      return {
        appData,
        recurringInstance: null,
        shouldGenerateDayPlanItem: false,
      }
    }

    const recurringInstanceResult = ensureRecurringInstance(
      appData,
      template,
      repeatRule,
      selectedDateKey,
      nowIso,
    )

    return {
      appData: recurringInstanceResult.appData,
      recurringInstance: recurringInstanceResult.recurringInstance,
      shouldGenerateDayPlanItem: true,
    }
  }

  const nextTargetDate = resolveAfterCompletionTargetDate(
    appData,
    template,
    selectedDateKey,
    repeatRule,
  )

  if (!nextTargetDate) {
    return {
      appData,
      recurringInstance: null,
      shouldGenerateDayPlanItem: false,
    }
  }

  const recurringInstanceResult = ensureRecurringInstance(
    appData,
    template,
    repeatRule,
    nextTargetDate,
    nowIso,
  )

  return {
    appData: recurringInstanceResult.appData,
    recurringInstance: recurringInstanceResult.recurringInstance,
    shouldGenerateDayPlanItem: true,
  }
}

const findExistingAutoGeneratedOccurrence = (
  appData: AppData,
  templateId: string,
  targetDate: string,
) =>
  appData.dayPlanItems.find(
    (item) =>
      item.source === 'auto_generated' &&
      item.templateId === templateId &&
      (item.targetDate === targetDate || item.originDate === targetDate),
  )

const isArchivedTemplate = (appData: AppData, templateId?: string) =>
  Boolean(
    templateId && appData.taskTemplates.find((template) => template.id === templateId)?.isArchived,
  )

const syncAutoGeneratedItem = (
  appData: AppData,
  candidate: AutoGeneratedCandidate,
  selectedDateKey: string,
  sortOrder: number,
  nowIso: string,
) => {
  const existingItem = findExistingAutoGeneratedOccurrence(appData, candidate.template.id, selectedDateKey)

  if (existingItem?.status === 'deleted') {
    return {
      appData,
      dayPlanItem: null,
    }
  }

  const shouldPreserveMovedOccurrence = Boolean(existingItem) && existingItem!.date > selectedDateKey
  const nextDate = shouldPreserveMovedOccurrence ? existingItem!.date : selectedDateKey
  const nextTimeBlock = shouldPreserveMovedOccurrence ? existingItem!.timeBlock : candidate.timeContext.timeBlock
  const nextTimeBlockSource = shouldPreserveMovedOccurrence
    ? existingItem!.timeBlockSource
    : candidate.timeContext.timeBlockSource
  const nextSortOrder = shouldPreserveMovedOccurrence ? existingItem!.sortOrder : sortOrder

  const baseItem = {
    date: nextDate,
    originDate: existingItem?.originDate ?? selectedDateKey,
    targetDate: selectedDateKey,
    deadlineDate:
      shouldPreserveMovedOccurrence && existingItem?.deadlineDate
        ? existingItem.deadlineDate
        : resolveRecurringDeadlineDate({
            templateDate: candidate.template.date,
            templateDeadlineDate: candidate.template.deadlineDate,
            occurrenceDate: nextDate,
          }),
    timeBlock: nextTimeBlock,
    timeBlockSource: nextTimeBlockSource,
    sortOrder: nextSortOrder,
    source: 'auto_generated' as const,
    templateId: candidate.template.id,
    recurringInstanceId: candidate.recurringInstance?.id,
    title: candidate.template.title,
    activityTypeId: candidate.template.activityTypeId,
    isNecessary: candidate.template.isNecessary,
    requiresPreparation: candidate.template.requiresPreparation,
    preparationNotes: candidate.template.preparationNotes,
    isSegmented: candidate.template.isStepped ? false : candidate.template.isSegmented,
    isStepped: candidate.template.isStepped,
    currentStep: candidate.template.isStepped ? candidate.template.currentStep : '',
    nextStep: candidate.template.isStepped ? candidate.template.nextStep : '',
    stepRootItemId: candidate.template.isStepped
      ? existingItem?.stepRootItemId ??
        existingItem?.id ??
        `day-plan-item-auto-${candidate.template.id}-${selectedDateKey}`
      : undefined,
    previousStepItemId: existingItem?.previousStepItemId,
    rootItemId:
      existingItem?.rootItemId ??
      existingItem?.id ??
      `day-plan-item-auto-${candidate.template.id}-${selectedDateKey}`,
  }

  if (existingItem) {
    const nextDayPlanItems = appData.dayPlanItems.map((item) =>
      item.id === existingItem.id ? { ...item, ...baseItem } : item,
    )

    return {
      appData: {
        ...appData,
        dayPlanItems: nextDayPlanItems,
      },
      dayPlanItem: nextDayPlanItems.find((item) => item.id === existingItem.id)!,
    }
  }

  const dayPlanItem: DayPlanItem = {
    id: `day-plan-item-auto-${candidate.template.id}-${selectedDateKey}`,
    createdAt: nowIso,
    updatedAt: nowIso,
    ...baseItem,
    rootItemId: `day-plan-item-auto-${candidate.template.id}-${selectedDateKey}`,
    progressState: candidate.recurringInstance?.progressState ?? 'not_started',
    progressPercent: candidate.recurringInstance?.progressPercent ?? 0,
    status: 'pending',
  }

  return {
    appData: {
      ...appData,
      dayPlanItems: [...appData.dayPlanItems, dayPlanItem],
    },
    dayPlanItem,
  }
}

const getAutoGeneratedTemplates = (appData: AppData, selectedDateKey: string) =>
  appData.taskTemplates.filter((template) => {
    if (template.isArchived) {
      return false
    }

    if (resolveRepeatRule(template).repeatType !== 'none') {
      return true
    }

    return template.date === selectedDateKey
  })

const sortCandidates = (candidates: AutoGeneratedCandidate[]) =>
  [...candidates].sort((left, right) => {
    const leftWeight =
      left.timeContext.timeBlockSource === 'mapped_day'
        ? 1
        : left.timeContext.timeBlockSource === 'default_day'
          ? 2
          : 3

    const rightWeight =
      right.timeContext.timeBlockSource === 'mapped_day'
        ? 1
        : right.timeContext.timeBlockSource === 'default_day'
          ? 2
          : 3

    if (leftWeight !== rightWeight) {
      return leftWeight - rightWeight
    }

    return left.template.createdAt.localeCompare(right.template.createdAt)
  })

const applySelectedDateStateChanges = async (
  dataPath: string,
  currentAppData: AppData,
  nextAppData: AppData,
) => {
  const currentRecurringInstancesById = new Map(
    currentAppData.recurringTaskInstances.map((instance) => [instance.id, instance]),
  )
  const currentDayPlanItemsById = new Map(
    currentAppData.dayPlanItems.map((item) => [item.id, item]),
  )

  for (const instance of nextAppData.recurringTaskInstances) {
    const current = currentRecurringInstancesById.get(instance.id)
    if (!current) {
      await createSqliteRecurringTaskInstance(dataPath, instance)
      continue
    }

    if (JSON.stringify(current) !== JSON.stringify(instance)) {
      await updateSqliteRecurringTaskInstance(dataPath, instance)
    }
  }

  for (const item of nextAppData.dayPlanItems) {
    const current = currentDayPlanItemsById.get(item.id)
    if (!current) {
      await createSqliteDayPlanItem(dataPath, item)
      continue
    }

    if (JSON.stringify(current) !== JSON.stringify(item)) {
      await updateSqliteDayPlanItem(dataPath, item)
    }
  }
}

const syncAutoGeneratedDayPlanForDateInAppData = (
  currentAppData: AppData,
  selectedDateInput: Date | string,
) => {
  const selectedDate =
    typeof selectedDateInput === 'string' ? parseDate(selectedDateInput) : new Date(selectedDateInput)
  const selectedDateKey = toDateString(selectedDate)
  const nowIso = new Date().toISOString()

  let nextAppData = currentAppData
  const candidates = getAutoGeneratedTemplates(currentAppData, selectedDateKey)
  const enrichedCandidates: AutoGeneratedCandidate[] = []

  for (const template of candidates) {
    if (resolveRepeatRule(template).repeatType !== 'afterCompletion' && hasConsumedTrigger(nextAppData, template.id, selectedDateKey)) {
      continue
    }

    const recurringResult = updateRecurringInstancesForTemplate(
      nextAppData,
      template,
      selectedDate,
      selectedDateKey,
      nowIso,
    )
    nextAppData = recurringResult.appData

    if (!recurringResult.shouldGenerateDayPlanItem) {
      continue
    }

    enrichedCandidates.push({
      template,
      recurringInstance: recurringResult.recurringInstance,
      timeContext: resolveTimeContext(template.sceneTagIds, currentAppData.sceneTags),
    })
  }

  const sortedCandidates = sortCandidates(enrichedCandidates)
  const syncedItems: DayPlanItem[] = []

  sortedCandidates.forEach((candidate, index) => {
    const syncResult = syncAutoGeneratedItem(nextAppData, candidate, selectedDateKey, index + 1, nowIso)
    nextAppData = syncResult.appData

    if (syncResult.dayPlanItem) {
      syncedItems.push(syncResult.dayPlanItem)
    }
  })

  const itemsToHide = nextAppData.dayPlanItems
    .filter(
      (item) =>
        item.source === 'auto_generated' &&
        item.targetDate === selectedDateKey &&
        !syncedItems.some((syncedItem) => syncedItem.id === item.id) &&
        item.status === 'pending' &&
        !isArchivedTemplate(nextAppData, item.templateId),
    )
    .map((item) => item.id)

  if (itemsToHide.length > 0) {
    nextAppData = {
      ...nextAppData,
      dayPlanItems: nextAppData.dayPlanItems.map((item) =>
        itemsToHide.includes(item.id)
          ? {
              ...item,
              status: 'deleted' as const,
            }
          : item,
      ),
    }
  }

  return nextAppData
}

const syncTodoCarryoversForDateInAppData = (appData: AppData, selectedDateInput: Date | string) => {
  const selectedDate =
    typeof selectedDateInput === 'string' ? parseDate(selectedDateInput) : new Date(selectedDateInput)
  const selectedDateKey = toDateString(selectedDate)
  const templateKindsById = getTemplateKindMap(appData)
  const latestByRoot = findLatestCarryableItemsByRoot(appData, selectedDateKey, templateKindsById)

  if (latestByRoot.size === 0) {
    return appData
  }

  const dayItems = appData.dayPlanItems.filter((item) => item.date === selectedDateKey)
  const nextSortOrder = {
    day:
      dayItems.filter((item) => item.timeBlock === 'day').reduce((max, item) => Math.max(max, item.sortOrder), 0) +
      1,
    night:
      dayItems.filter((item) => item.timeBlock === 'night').reduce((max, item) => Math.max(max, item.sortOrder), 0) +
      1,
  }

  const carryoverItems = [...latestByRoot.values()]
    .filter((item) => !hasRootItemOnDate(appData.dayPlanItems, selectedDateKey, getRootItemId(item)))
    .sort((left, right) => {
      if (left.timeBlock !== right.timeBlock) {
        return left.timeBlock === 'day' ? -1 : 1
      }

      return compareItemsByDateDesc(left, right)
    })

  if (carryoverItems.length === 0) {
    return appData
  }

  const updatedItemsById = new Map<string, DayPlanItem>()

  for (const item of carryoverItems) {
    const sortOrder = nextSortOrder[item.timeBlock]
    nextSortOrder[item.timeBlock] += 1

    updatedItemsById.set(item.id, {
      ...item,
      date: selectedDateKey,
      originDate: resolveOriginDate(item),
      sortOrder,
      updatedAt: new Date().toISOString(),
    })
  }

  return {
    ...appData,
    dayPlanItems: appData.dayPlanItems.map((dayPlanItem) => updatedItemsById.get(dayPlanItem.id) ?? dayPlanItem),
  }
}

export const prepareSelectedDateState = async (
  dataPath: string,
  selectedDateKey: string,
  options?: {
    includeCarryovers?: boolean
  },
) => {
  const currentAppData = getSqliteAppData(dataPath)

  if (!currentAppData) {
    return {
      updated: false,
      selectedDateKey,
    }
  }

  let nextAppData = syncAutoGeneratedDayPlanForDateInAppData(currentAppData, selectedDateKey)

  if (options?.includeCarryovers) {
    nextAppData = syncTodoCarryoversForDateInAppData(nextAppData, selectedDateKey)
  }

  if (JSON.stringify(currentAppData) === JSON.stringify(nextAppData)) {
    return {
      updated: false,
      selectedDateKey,
    }
  }

  await applySelectedDateStateChanges(dataPath, currentAppData, nextAppData)

  return {
    updated: true,
    selectedDateKey,
  }
}
