import { useEffect, useMemo, useState } from 'react'

import { SurfaceCard } from '@/components/ui/SurfaceCard'
import {
  createDecisionSelectedDayPlanItem,
  getDecisionRecommendations,
  listDecisionActivityTypes,
} from '@/features/decision'
import { syncAutoGeneratedDayPlanForDate } from '@/features/recurrence'
import { CreateTaskTemplateForm, TemplateManagerPanel } from '@/features/templates'
import { TodoModePanel } from '@/features/todo'
import { appDataRepository } from '@/db'
import type { ActivityType, DayPlanItem, TaskTemplate, TimeBlock } from '@/types'

type HomeMode = 'decision' | 'todo'

type TimeContext = 'day' | 'night'

type AutoGeneratedViewState = {
  isLoading: boolean
  errorMessage: string | null
  dayAutoItems: DayPlanItem[]
  nightAutoItems: DayPlanItem[]
  dayDecisionItems: DayPlanItem[]
  nightDecisionItems: DayPlanItem[]
}

type RecommendationPanelState = {
  timeBlock: TimeBlock
  activityTypeId: string
  recommended: TaskTemplate | null
  candidates: TaskTemplate[]
  errorMessage: string | null
  isLoading: boolean
}

const formatHeaderLabel = (date: Date) =>
  new Intl.DateTimeFormat('zh-CN', {
    month: 'long',
    day: 'numeric',
    weekday: 'long',
  }).format(date)

const formatMetaLabel = (date: Date) =>
  new Intl.DateTimeFormat('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(date)

const addDays = (date: Date, days: number) => {
  const nextDate = new Date(date)
  nextDate.setDate(nextDate.getDate() + days)

  return nextDate
}

const decisionContexts: Array<{
  id: TimeContext
  title: string
  description: string
  entryLabel: string
  placeholderTitle: string
  placeholderBody: string
}> = [
  {
    id: 'day',
    title: '白天语境',
    description: '当前只承接信息结构，后续自动事项与手动事项会汇入这一段。',
    entryLabel: '为白天增加安排',
    placeholderTitle: '白天计划占位',
    placeholderBody:
      'Task 8 只落单列计划区结构，不在这里计算默认白天、明确白天或真实排序逻辑。',
  },
  {
    id: 'night',
    title: '晚上语境',
    description: '当前先提供独立样式与信息承接位置，夜间推荐和语境切换留到后续任务。',
    entryLabel: '为晚上增加安排',
    placeholderTitle: '晚上计划占位',
    placeholderBody:
      'Task 8 不实现拖动后语境切换，也不根据当前位置改变条目语义。',
  },
]

function AutoGeneratedItemsSection({
  items,
  emptyTitle,
  emptyBody,
}: {
  items: DayPlanItem[]
  emptyTitle: string
  emptyBody: string
}) {
  if (items.length === 0) {
    return (
      <article className="plan-placeholder-card">
        <p className="eyebrow">自动事项</p>
        <h5>{emptyTitle}</h5>
        <p>{emptyBody}</p>
      </article>
    )
  }

  return (
    <div className="auto-generated-list">
      {items.map((item) => (
        <article className="auto-generated-card" key={item.id}>
          <div className="auto-generated-card__header">
            <div>
              <p className="eyebrow">自动生成</p>
              <h5>{item.title}</h5>
            </div>
            <span
              className={
                item.isNecessary ? 'status-chip status-chip--necessary' : 'status-chip'
              }
            >
              {item.isNecessary ? '必要事项' : '普通事项'}
            </span>
          </div>

          <div className="auto-generated-card__meta">
            <span>{item.timeBlock === 'day' ? '白天' : '晚上'}</span>
            <span>{item.timeBlockSource}</span>
            {item.isSegmented ? <span>进度 {item.progressPercent}%</span> : null}
            {item.requiresPreparation ? <span>含准备提示</span> : null}
          </div>

          {item.requiresPreparation && item.preparationNotes ? (
            <p className="auto-generated-card__notes">{item.preparationNotes}</p>
          ) : null}
        </article>
      ))}
    </div>
  )
}

function DecisionSelectedItemsSection({ items }: { items: DayPlanItem[] }) {
  if (items.length === 0) {
    return (
      <article className="plan-placeholder-card">
        <p className="eyebrow">手动事项</p>
        <h5>当前语境还没有手动选入事项</h5>
        <p>Task 10 会把你从推荐流程中确认的事项写成 `decision_selected` 实例并显示在这里。</p>
      </article>
    )
  }

  return (
    <div className="auto-generated-list">
      {items.map((item) => (
        <article className="auto-generated-card" key={item.id}>
          <div className="auto-generated-card__header">
            <div>
              <p className="eyebrow">决策选入</p>
              <h5>{item.title}</h5>
            </div>
            <span className="status-chip">手动选入</span>
          </div>

          <div className="auto-generated-card__meta">
            <span>{item.timeBlock === 'day' ? '白天' : '晚上'}</span>
            <span>{item.timeBlockSource}</span>
            <span>targetDate {item.targetDate ?? item.date}</span>
            {item.isSegmented ? <span>进度 {item.progressPercent}%</span> : null}
            {item.requiresPreparation ? <span>含准备提示</span> : null}
          </div>

          {item.requiresPreparation && item.preparationNotes ? (
            <p className="auto-generated-card__notes">{item.preparationNotes}</p>
          ) : null}
        </article>
      ))}
    </div>
  )
}

function RecommendationInlineCard({
  activityTypes,
  panelState,
  onActivityTypeChange,
  onConfirm,
  onClose,
}: {
  activityTypes: ActivityType[]
  panelState: RecommendationPanelState
  onActivityTypeChange: (activityTypeId: string) => void
  onConfirm: (template: TaskTemplate) => void
  onClose: () => void
}) {
  return (
    <div className="recommendation-card">
      <div className="recommendation-card__header">
        <div>
          <p className="eyebrow">增加安排</p>
          <h5>{panelState.timeBlock === 'day' ? '白天推荐' : '晚上推荐'}</h5>
        </div>
        <button className="ghost-button" type="button" onClick={onClose}>
          关闭
        </button>
      </div>

      <label className="editor-field">
        <span>活动类型</span>
        <select
          value={panelState.activityTypeId}
          onChange={(event) => {
            onActivityTypeChange(event.target.value)
          }}
        >
          {activityTypes.map((activityType) => (
            <option key={activityType.id} value={activityType.id}>
              {activityType.name}
            </option>
          ))}
        </select>
      </label>

      {panelState.isLoading ? (
        <p className="form-message">正在根据当前日期与语境筛选推荐候选。</p>
      ) : panelState.errorMessage ? (
        <p className="form-message form-message--danger">{panelState.errorMessage}</p>
      ) : (
        <>
          <div className="recommendation-card__recommended">
            <p className="eyebrow">推荐第一项</p>
            {panelState.recommended ? (
              <div className="plan-placeholder-card">
                <h5>{panelState.recommended.title}</h5>
                <p>
                  当前推荐已排除自动事项、同语境重复项，并优先展示更匹配当前语境的模板。
                </p>
                <button
                  className="primary-button"
                  type="button"
                  onClick={() => {
                    onConfirm(panelState.recommended as TaskTemplate)
                  }}
                >
                  直接加入
                </button>
              </div>
            ) : (
              <div className="plan-placeholder-card">
                <h5>当前没有默认推荐项</h5>
                <p>可能是候选都已在另一语境出现，或当前筛选结果为空。你仍可查看候选列表。</p>
              </div>
            )}
          </div>

          <div className="recommendation-card__candidates">
            <p className="eyebrow">候选列表</p>
            {panelState.candidates.length === 0 ? (
              <div className="plan-placeholder-card">
                <h5>暂无候选项</h5>
                <p>当前活动类型下没有符合当前日期与语境条件的非必要模板。</p>
              </div>
            ) : (
              <div className="candidate-list">
                {panelState.candidates.map((candidate) => (
                  <article className="candidate-item" key={candidate.id}>
                    <div>
                      <h6>{candidate.title}</h6>
                      <p>
                        兴趣程度 {candidate.interestLevel} · 日期锚点 {candidate.date}
                      </p>
                    </div>
                    <button
                      className="ghost-button"
                      type="button"
                      onClick={() => {
                        onConfirm(candidate)
                      }}
                    >
                      选中
                    </button>
                  </article>
                ))}
              </div>
            )}
          </div>
        </>
      )}
    </div>
  )
}

function DecisionModePanel({ selectedDate }: { selectedDate: Date }) {
  const [activityTypes, setActivityTypes] = useState<ActivityType[]>([])
  const [viewState, setViewState] = useState<AutoGeneratedViewState>({
    isLoading: true,
    errorMessage: null,
    dayAutoItems: [],
    nightAutoItems: [],
    dayDecisionItems: [],
    nightDecisionItems: [],
  })
  const [activePanel, setActivePanel] = useState<RecommendationPanelState | null>(null)

  const loadDecisionViewState = async () => {
    const appData = await appDataRepository.get()
    const selectedDateKey = `${selectedDate.getFullYear()}-${String(
      selectedDate.getMonth() + 1,
    ).padStart(2, '0')}-${String(selectedDate.getDate()).padStart(2, '0')}`
    const items = appData.dayPlanItems.filter(
      (item) => item.date === selectedDateKey && item.status !== 'deleted',
    )
    const sortItems = (source: 'auto_generated' | 'decision_selected', timeBlock: TimeBlock) =>
      items
        .filter((item) => item.source === source && item.timeBlock === timeBlock)
        .sort((left, right) => left.sortOrder - right.sortOrder)

    return {
      dayAutoItems: sortItems('auto_generated', 'day'),
      nightAutoItems: sortItems('auto_generated', 'night'),
      dayDecisionItems: sortItems('decision_selected', 'day'),
      nightDecisionItems: sortItems('decision_selected', 'night'),
    }
  }

  useEffect(() => {
    let cancelled = false
    setActivePanel(null)

    setViewState((current) => ({
      ...current,
      isLoading: true,
      errorMessage: null,
    }))

    void syncAutoGeneratedDayPlanForDate(selectedDate)
      .then(async () => {
        if (cancelled) {
          return
        }

        const [nextViewState, nextActivityTypes] = await Promise.all([
          loadDecisionViewState(),
          listDecisionActivityTypes(),
        ])

        setViewState({
          isLoading: false,
          errorMessage: null,
          ...nextViewState,
        })
        setActivityTypes(nextActivityTypes)
      })
      .catch((error: unknown) => {
        if (cancelled) {
          return
        }

        setViewState({
          isLoading: false,
          errorMessage:
            error instanceof Error ? error.message : '自动事项同步失败，请稍后重试。',
          dayAutoItems: [],
          nightAutoItems: [],
          dayDecisionItems: [],
          nightDecisionItems: [],
        })
      })

    return () => {
      cancelled = true
    }
  }, [selectedDate])

  const openRecommendationPanel = async (timeBlock: TimeBlock) => {
    const defaultActivityTypeId = activityTypes[0]?.id

    if (!defaultActivityTypeId) {
      return
    }

    setActivePanel({
      timeBlock,
      activityTypeId: defaultActivityTypeId,
      recommended: null,
      candidates: [],
      errorMessage: null,
      isLoading: true,
    })

    try {
      const recommendation = await getDecisionRecommendations({
        selectedDate,
        timeBlock,
        activityTypeId: defaultActivityTypeId,
      })

      setActivePanel({
        timeBlock,
        activityTypeId: defaultActivityTypeId,
        recommended: recommendation.recommended,
        candidates: recommendation.candidates,
        errorMessage: null,
        isLoading: false,
      })
    } catch (error: unknown) {
      setActivePanel({
        timeBlock,
        activityTypeId: defaultActivityTypeId,
        recommended: null,
        candidates: [],
        errorMessage:
          error instanceof Error ? error.message : '推荐候选读取失败，请稍后重试。',
        isLoading: false,
      })
    }
  }

  const changeRecommendationActivityType = async (activityTypeId: string) => {
    if (!activePanel) {
      return
    }

    setActivePanel({
      ...activePanel,
      activityTypeId,
      isLoading: true,
      errorMessage: null,
    })

    try {
      const recommendation = await getDecisionRecommendations({
        selectedDate,
        timeBlock: activePanel.timeBlock,
        activityTypeId,
      })

      setActivePanel({
        timeBlock: activePanel.timeBlock,
        activityTypeId,
        recommended: recommendation.recommended,
        candidates: recommendation.candidates,
        errorMessage: null,
        isLoading: false,
      })
    } catch (error: unknown) {
      setActivePanel({
        timeBlock: activePanel.timeBlock,
        activityTypeId,
        recommended: null,
        candidates: [],
        errorMessage:
          error instanceof Error ? error.message : '推荐候选读取失败，请稍后重试。',
        isLoading: false,
      })
    }
  }

  const confirmRecommendation = async (template: TaskTemplate) => {
    if (!activePanel) {
      return
    }

    await createDecisionSelectedDayPlanItem({
      selectedDate,
      timeBlock: activePanel.timeBlock,
      template,
    })

    const nextViewState = await loadDecisionViewState()
    setViewState((current) => ({
      ...current,
      ...nextViewState,
    }))
    setActivePanel(null)
  }

  return (
    <div className="mode-panel">
      <div className="mode-panel__intro">
        <p className="eyebrow">Decision Mode</p>
        <h2>按整天查看的一列计划区</h2>
        <p>
          本轮主落地决策模式结构。这里先建立单列计划区、白天/晚上语境段和“增加安排”入口，
          但不提前实现自动生成或推荐逻辑。
        </p>
      </div>

      <div className="plan-column">
        <div className="plan-column__header">
          <div>
            <p className="eyebrow">当前计划日期</p>
            <h3>{formatHeaderLabel(selectedDate)}</h3>
          </div>
          <p className="plan-column__meta">
            当前只承接信息结构，不承接排序语义与业务计算。
          </p>
        </div>

        <div className="plan-column__timeline" aria-label="单列计划区">
          {decisionContexts.map((context) => (
            <section
              key={context.id}
              className={
                context.id === 'day'
                  ? 'time-context time-context--day'
                  : 'time-context time-context--night'
              }
            >
              <div className="time-context__header">
                <div>
                  <p className="eyebrow">{context.id === 'day' ? 'Day' : 'Night'}</p>
                  <h4>{context.title}</h4>
                </div>
                <p>{context.description}</p>
              </div>

              <div className="plan-placeholder-list">
                {viewState.isLoading ? (
                  <article className="plan-placeholder-card">
                    <p className="eyebrow">自动事项同步中</p>
                    <h5>正在读取并落库当前日期的自动事项</h5>
                    <p>Task 9 按“查看即惰性落库”同步当前查看日期相关的自动实例。</p>
                  </article>
                ) : viewState.errorMessage ? (
                  <article className="plan-placeholder-card plan-placeholder-card--danger">
                    <p className="eyebrow">自动事项同步失败</p>
                    <h5>{context.placeholderTitle}</h5>
                    <p>{viewState.errorMessage}</p>
                  </article>
                ) : (
                  <AutoGeneratedItemsSection
                    items={
                      context.id === 'day'
                        ? viewState.dayAutoItems
                        : viewState.nightAutoItems
                    }
                    emptyTitle={context.placeholderTitle}
                    emptyBody={context.placeholderBody}
                  />
                )}

                <DecisionSelectedItemsSection
                  items={
                    context.id === 'day'
                      ? viewState.dayDecisionItems
                      : viewState.nightDecisionItems
                  }
                />

                {activePanel?.timeBlock === context.id ? (
                  <RecommendationInlineCard
                    activityTypes={activityTypes}
                    panelState={activePanel}
                    onActivityTypeChange={(activityTypeId) => {
                      void changeRecommendationActivityType(activityTypeId)
                    }}
                    onConfirm={(template) => {
                      void confirmRecommendation(template)
                    }}
                    onClose={() => {
                      setActivePanel(null)
                    }}
                  />
                ) : null}
              </div>

              <button
                className="ghost-button plan-entry-button"
                type="button"
                onClick={() => {
                  void openRecommendationPanel(context.id)
                }}
              >
                {context.entryLabel}
              </button>
            </section>
          ))}
        </div>
      </div>
    </div>
  )
}

export function HomePage() {
  const [mode, setMode] = useState<HomeMode>('decision')
  const [selectedDate, setSelectedDate] = useState(() => new Date())
  const [showTemplateManager, setShowTemplateManager] = useState(false)

  const selectedHeaderLabel = useMemo(
    () => formatHeaderLabel(selectedDate),
    [selectedDate],
  )
  const selectedMetaLabel = useMemo(
    () => formatMetaLabel(selectedDate),
    [selectedDate],
  )

  return (
    <div className="home-layout">
      <section className="home-layout__top">
        <SurfaceCard
          title="顶部信息区"
          description="主页面已进入真实结构阶段。当前顶部只承接日期信息与天气占位，不接入真实天气服务。"
        >
          <div className="topbar-panel">
            <div className="topbar-panel__date">
              <p className="eyebrow">当前选中日期</p>
              <h2>{selectedHeaderLabel}</h2>
              <p>{selectedMetaLabel}</p>
            </div>

            <div className="topbar-panel__actions">
              <div className="date-switcher" aria-label="日期切换">
                <button
                  className="ghost-button"
                  type="button"
                  onClick={() => {
                    setSelectedDate((current) => addDays(current, -1))
                  }}
                >
                  前一天
                </button>
                <button
                  className="ghost-button"
                  type="button"
                  onClick={() => {
                    setSelectedDate(new Date())
                  }}
                >
                  今天
                </button>
                <button
                  className="ghost-button"
                  type="button"
                  onClick={() => {
                    setSelectedDate((current) => addDays(current, 1))
                  }}
                >
                  后一天
                </button>
              </div>

              <div className="weather-placeholder" aria-label="天气占位">
                <span className="weather-placeholder__icon">◌</span>
                <div>
                  <p className="eyebrow">天气占位</p>
                  <p>V1 不接真实天气 API</p>
                </div>
              </div>
            </div>
          </div>
        </SurfaceCard>
      </section>

      <section className="home-layout__switcher">
        <SurfaceCard
          title="模式切换区"
          description="Task 8 将模式切换做成真实页面内状态。决策模式是真实骨架，Todo 模式只做结构占位。"
        >
          <div className="mode-switcher" role="tablist" aria-label="主页面模式切换">
            <button
              className={
                mode === 'todo'
                  ? 'mode-switcher__button mode-switcher__button--active'
                  : 'mode-switcher__button'
              }
              type="button"
              role="tab"
              aria-selected={mode === 'todo'}
              onClick={() => {
                setMode('todo')
              }}
            >
              Todo 模式
            </button>

            <button
              className={
                mode === 'decision'
                  ? 'mode-switcher__button mode-switcher__button--active'
                  : 'mode-switcher__button'
              }
              type="button"
              role="tab"
              aria-selected={mode === 'decision'}
              onClick={() => {
                setMode('decision')
              }}
            >
              决策模式
            </button>
          </div>
        </SurfaceCard>
      </section>

      <section className="home-layout__main">
        <SurfaceCard
          title="主内容区"
          description="决策模式是本轮主落地视图。Todo 模式只保留结构占位，不接入真实待办列表。"
        >
          {mode === 'decision' ? (
            <DecisionModePanel selectedDate={selectedDate} />
          ) : (
            <TodoModePanel selectedDate={selectedDate} />
          )}
        </SurfaceCard>
      </section>

      <section className="home-layout__composer">
        <SurfaceCard
          title="底部添加区"
          description="新增条目录入与模板管理放在同一区域。新增和编辑共用同一套字段结构，但编辑只影响未来自动生成与未来推荐。"
        >
          <div className="composer-toolbar">
            <button
              className="ghost-button"
              type="button"
              onClick={() => {
                setShowTemplateManager((current) => !current)
              }}
            >
              {showTemplateManager ? '收起模板管理' : '管理已有条目'}
            </button>
          </div>

          {showTemplateManager ? <TemplateManagerPanel /> : null}

          <CreateTaskTemplateForm />
        </SurfaceCard>
      </section>
    </div>
  )
}
