import { useEffect, useMemo, useState } from 'react'

import { SurfaceCard } from '@/components/ui/SurfaceCard'
import {
  createDecisionSelectedDayPlanItem,
  getDecisionRecommendations,
  listDecisionActivityTypes,
} from '@/features/decision'
import { syncAutoGeneratedDayPlanForDate } from '@/features/recurrence'
import { CreateTaskTemplateForm, TemplateManagerPanel } from '@/features/templates'
import { TodoModePanel } from '@/features/todo'
import { appDataRepository } from '@/db'
import type { ActivityType, DayPlanItem, TaskTemplate, TimeBlock } from '@/types'

type HomeMode = 'decision' | 'todo'
type TimeContext = 'day' | 'night'

type AutoGeneratedViewState = {
  isLoading: boolean
  errorMessage: string | null
  dayAutoItems: DayPlanItem[]
  nightAutoItems: DayPlanItem[]
  dayDecisionItems: DayPlanItem[]
  nightDecisionItems: DayPlanItem[]
}

type RecommendationPanelState = {
  timeBlock: TimeBlock
  activityTypeId: string
  recommended: TaskTemplate | null
  candidates: TaskTemplate[]
  errorMessage: string | null
  isLoading: boolean
}

const formatHeaderLabel = (date: Date) =>
  new Intl.DateTimeFormat('zh-CN', {
    month: 'long',
    day: 'numeric',
    weekday: 'long',
  }).format(date)

const formatMetaLabel = (date: Date) =>
  new Intl.DateTimeFormat('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(date)

const addDays = (date: Date, days: number) => {
  const nextDate = new Date(date)
  nextDate.setDate(nextDate.getDate() + days)

  return nextDate
}

const decisionContexts: Array<{
  id: TimeContext
  label: string
  actionLabel: string
  emptyLabel: string
}> = [
  {
    id: 'day',
    label: '白天',
    actionLabel: '添加白天安排',
    emptyLabel: '白天还没有安排',
  },
  {
    id: 'night',
    label: '晚上',
    actionLabel: '添加晚上安排',
    emptyLabel: '晚上还没有安排',
  },
]

const sourceChipLabel: Record<DayPlanItem['source'], string> = {
  auto_generated: '自动',
  decision_selected: '已选',
  manual_temporary: '临时',
}

const timeBlockLabel: Record<TimeBlock, string> = {
  day: '日间',
  night: '夜间',
}

function renderItemTags(item: DayPlanItem, includeTimeBlock = false) {
  const tags = [sourceChipLabel[item.source]]

  if (includeTimeBlock) {
    tags.push(timeBlockLabel[item.timeBlock])
  }

  if (item.isNecessary) {
    tags.push('必要')
  }

  if (item.isSegmented) {
    tags.push(`分次 ${item.progressPercent}%`)
  }

  if (item.requiresPreparation) {
    tags.push('准备')
  }

  if (item.status === 'completed') {
    tags.push('已完成')
  }

  return tags
}

function ItemCard({
  item,
  emphasis,
}: {
  item: DayPlanItem
  emphasis?: 'day' | 'night'
}) {
  const tags = renderItemTags(item)

  return (
    <article
      className={
        emphasis === 'night'
          ? 'item-card item-card--night'
          : emphasis === 'day'
            ? 'item-card item-card--day'
            : 'item-card'
      }
    >
      <div className="item-card__header">
        <h5>{item.title}</h5>
        <div className="tag-row">
          {tags.map((tag) => (
            <span
              key={tag}
              className={tag === '必要' ? 'status-chip status-chip--necessary' : 'status-chip'}
            >
              {tag}
            </span>
          ))}
        </div>
      </div>

      {item.requiresPreparation && item.preparationNotes ? (
        <p className="item-card__note">{item.preparationNotes}</p>
      ) : null}
    </article>
  )
}

function AutoGeneratedItemsSection({
  items,
  emptyLabel,
  emphasis,
}: {
  items: DayPlanItem[]
  emptyLabel: string
  emphasis: 'day' | 'night'
}) {
  if (items.length === 0) {
    return (
      <article className="empty-state-card">
        <p>{emptyLabel}</p>
      </article>
    )
  }

  return (
    <div className="item-stack">
      {items.map((item) => (
        <ItemCard key={item.id} item={item} emphasis={emphasis} />
      ))}
    </div>
  )
}

function DecisionSelectedItemsSection({
  items,
  emphasis,
}: {
  items: DayPlanItem[]
  emphasis: 'day' | 'night'
}) {
  if (items.length === 0) {
    return null
  }

  return (
    <div className="item-stack">
      {items.map((item) => (
        <ItemCard key={item.id} item={item} emphasis={emphasis} />
      ))}
    </div>
  )
}

function RecommendationInlineCard({
  activityTypes,
  panelState,
  onActivityTypeChange,
  onConfirm,
  onClose,
}: {
  activityTypes: ActivityType[]
  panelState: RecommendationPanelState
  onActivityTypeChange: (activityTypeId: string) => void
  onConfirm: (template: TaskTemplate) => void
  onClose: () => void
}) {
  return (
    <div className="recommendation-card">
      <div className="recommendation-card__header">
        <div>
          <p className="eyebrow">增加安排</p>
          <h5>{panelState.timeBlock === 'day' ? '白天候选' : '晚上候选'}</h5>
        </div>
        <button className="ghost-button" type="button" onClick={onClose}>
          收起
        </button>
      </div>

      <label className="editor-field">
        <span>活动类型</span>
        <select
          value={panelState.activityTypeId}
          onChange={(event) => {
            onActivityTypeChange(event.target.value)
          }}
        >
          {activityTypes.map((activityType) => (
            <option key={activityType.id} value={activityType.id}>
              {activityType.name}
            </option>
          ))}
        </select>
      </label>

      {panelState.isLoading ? (
        <p className="form-message">正在加载候选...</p>
      ) : panelState.errorMessage ? (
        <p className="form-message form-message--danger">{panelState.errorMessage}</p>
      ) : (
        <div className="recommendation-card__body">
          <div className="recommendation-block">
            <div className="section-heading">
              <h6>推荐</h6>
            </div>

            {panelState.recommended ? (
              <article className="candidate-item candidate-item--recommended">
                <div>
                  <h6>{panelState.recommended.title}</h6>
                  <div className="tag-row">
                    <span className="status-chip">
                      兴趣 {panelState.recommended.interestLevel}
                    </span>
                    <span className="status-chip">{panelState.recommended.date}</span>
                  </div>
                </div>
                <button
                  className="primary-button"
                  type="button"
                  onClick={() => {
                    onConfirm(panelState.recommended as TaskTemplate)
                  }}
                >
                  加入
                </button>
              </article>
            ) : (
              <div className="empty-state-card">
                <p>没有默认推荐</p>
              </div>
            )}
          </div>

          <div className="recommendation-block">
            <div className="section-heading">
              <h6>候选列表</h6>
            </div>

            {panelState.candidates.length === 0 ? (
              <div className="empty-state-card">
                <p>没有可选候选</p>
              </div>
            ) : (
              <div className="candidate-list">
                {panelState.candidates.map((candidate) => (
                  <article className="candidate-item" key={candidate.id}>
                    <div>
                      <h6>{candidate.title}</h6>
                      <div className="tag-row">
                        <span className="status-chip">兴趣 {candidate.interestLevel}</span>
                        <span className="status-chip">{candidate.date}</span>
                      </div>
                    </div>
                    <button
                      className="ghost-button"
                      type="button"
                      onClick={() => {
                        onConfirm(candidate)
                      }}
                    >
                      选中
                    </button>
                  </article>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

function DecisionModePanel({ selectedDate }: { selectedDate: Date }) {
  const [activityTypes, setActivityTypes] = useState<ActivityType[]>([])
  const [viewState, setViewState] = useState<AutoGeneratedViewState>({
    isLoading: true,
    errorMessage: null,
    dayAutoItems: [],
    nightAutoItems: [],
    dayDecisionItems: [],
    nightDecisionItems: [],
  })
  const [activePanel, setActivePanel] = useState<RecommendationPanelState | null>(null)

  const loadDecisionViewState = async () => {
    const appData = await appDataRepository.get()
    const selectedDateKey = `${selectedDate.getFullYear()}-${String(
      selectedDate.getMonth() + 1,
    ).padStart(2, '0')}-${String(selectedDate.getDate()).padStart(2, '0')}`
    const items = appData.dayPlanItems.filter(
      (item) => item.date === selectedDateKey && item.status !== 'deleted',
    )
    const sortItems = (source: 'auto_generated' | 'decision_selected', timeBlock: TimeBlock) =>
      items
        .filter((item) => item.source === source && item.timeBlock === timeBlock)
        .sort((left, right) => left.sortOrder - right.sortOrder)

    return {
      dayAutoItems: sortItems('auto_generated', 'day'),
      nightAutoItems: sortItems('auto_generated', 'night'),
      dayDecisionItems: sortItems('decision_selected', 'day'),
      nightDecisionItems: sortItems('decision_selected', 'night'),
    }
  }

  useEffect(() => {
    let cancelled = false
    setActivePanel(null)

    setViewState((current) => ({
      ...current,
      isLoading: true,
      errorMessage: null,
    }))

    void syncAutoGeneratedDayPlanForDate(selectedDate)
      .then(async () => {
        if (cancelled) {
          return
        }

        const [nextViewState, nextActivityTypes] = await Promise.all([
          loadDecisionViewState(),
          listDecisionActivityTypes(),
        ])

        setViewState({
          isLoading: false,
          errorMessage: null,
          ...nextViewState,
        })
        setActivityTypes(nextActivityTypes)
      })
      .catch((error: unknown) => {
        if (cancelled) {
          return
        }

        setViewState({
          isLoading: false,
          errorMessage:
            error instanceof Error ? error.message : '自动事项读取失败，请稍后重试。',
          dayAutoItems: [],
          nightAutoItems: [],
          dayDecisionItems: [],
          nightDecisionItems: [],
        })
      })

    return () => {
      cancelled = true
    }
  }, [selectedDate])

  const openRecommendationPanel = async (timeBlock: TimeBlock) => {
    const defaultActivityTypeId = activityTypes[0]?.id

    if (!defaultActivityTypeId) {
      return
    }

    setActivePanel({
      timeBlock,
      activityTypeId: defaultActivityTypeId,
      recommended: null,
      candidates: [],
      errorMessage: null,
      isLoading: true,
    })

    try {
      const recommendation = await getDecisionRecommendations({
        selectedDate,
        timeBlock,
        activityTypeId: defaultActivityTypeId,
      })

      setActivePanel({
        timeBlock,
        activityTypeId: defaultActivityTypeId,
        recommended: recommendation.recommended,
        candidates: recommendation.candidates,
        errorMessage: null,
        isLoading: false,
      })
    } catch (error: unknown) {
      setActivePanel({
        timeBlock,
        activityTypeId: defaultActivityTypeId,
        recommended: null,
        candidates: [],
        errorMessage:
          error instanceof Error ? error.message : '推荐候选读取失败，请稍后重试。',
        isLoading: false,
      })
    }
  }

  const changeRecommendationActivityType = async (activityTypeId: string) => {
    if (!activePanel) {
      return
    }

    setActivePanel({
      ...activePanel,
      activityTypeId,
      isLoading: true,
      errorMessage: null,
    })

    try {
      const recommendation = await getDecisionRecommendations({
        selectedDate,
        timeBlock: activePanel.timeBlock,
        activityTypeId,
      })

      setActivePanel({
        timeBlock: activePanel.timeBlock,
        activityTypeId,
        recommended: recommendation.recommended,
        candidates: recommendation.candidates,
        errorMessage: null,
        isLoading: false,
      })
    } catch (error: unknown) {
      setActivePanel({
        timeBlock: activePanel.timeBlock,
        activityTypeId,
        recommended: null,
        candidates: [],
        errorMessage:
          error instanceof Error ? error.message : '推荐候选读取失败，请稍后重试。',
        isLoading: false,
      })
    }
  }

  const confirmRecommendation = async (template: TaskTemplate) => {
    if (!activePanel) {
      return
    }

    await createDecisionSelectedDayPlanItem({
      selectedDate,
      timeBlock: activePanel.timeBlock,
      template,
    })

    const nextViewState = await loadDecisionViewState()
    setViewState((current) => ({
      ...current,
      ...nextViewState,
    }))
    setActivePanel(null)
  }

  return (
    <div className="mode-panel">
      <div className="mode-panel__summary">
        <div>
          <p className="eyebrow">决策模式</p>
          <h2>{formatHeaderLabel(selectedDate)}</h2>
        </div>
        <span className="status-chip">{viewState.isLoading ? '同步中' : '已更新'}</span>
      </div>

      {viewState.errorMessage ? (
        <div className="empty-state-card empty-state-card--danger">
          <p>{viewState.errorMessage}</p>
        </div>
      ) : null}

      <div className="plan-column__timeline" aria-label="单列计划区">
        {decisionContexts.map((context) => {
          const autoItems =
            context.id === 'day' ? viewState.dayAutoItems : viewState.nightAutoItems
          const selectedItems =
            context.id === 'day' ? viewState.dayDecisionItems : viewState.nightDecisionItems

          return (
            <section
              key={context.id}
              className={
                context.id === 'day'
                  ? 'time-context time-context--day'
                  : 'time-context time-context--night'
              }
            >
              <div className="time-context__header">
                <div>
                  <p className="eyebrow">{context.id === 'day' ? 'Day' : 'Night'}</p>
                  <h4>{context.label}</h4>
                </div>
                <button
                  className="ghost-button"
                  type="button"
                  onClick={() => {
                    void openRecommendationPanel(context.id)
                  }}
                >
                  {context.actionLabel}
                </button>
              </div>

              {viewState.isLoading ? (
                <div className="empty-state-card">
                  <p>正在同步事项...</p>
                </div>
              ) : (
                <>
                  <AutoGeneratedItemsSection
                    items={autoItems}
                    emptyLabel={context.emptyLabel}
                    emphasis={context.id}
                  />
                  <DecisionSelectedItemsSection items={selectedItems} emphasis={context.id} />
                </>
              )}

              {activePanel?.timeBlock === context.id ? (
                <RecommendationInlineCard
                  activityTypes={activityTypes}
                  panelState={activePanel}
                  onActivityTypeChange={(activityTypeId) => {
                    void changeRecommendationActivityType(activityTypeId)
                  }}
                  onConfirm={(template) => {
                    void confirmRecommendation(template)
                  }}
                  onClose={() => {
                    setActivePanel(null)
                  }}
                />
              ) : null}
            </section>
          )
        })}
      </div>
    </div>
  )
}

export function HomePage() {
  const [mode, setMode] = useState<HomeMode>('decision')
  const [selectedDate, setSelectedDate] = useState(() => new Date())
  const [showComposer, setShowComposer] = useState(false)
  const [showTemplateManager, setShowTemplateManager] = useState(false)

  const selectedHeaderLabel = useMemo(
    () => formatHeaderLabel(selectedDate),
    [selectedDate],
  )
  const selectedMetaLabel = useMemo(
    () => formatMetaLabel(selectedDate),
    [selectedDate],
  )

  return (
    <div className="home-layout">
      <section className="home-appbar">
        <div className="home-appbar__main">
          <div className="home-appbar__title">
            <p className="eyebrow">Today</p>
            <h2>{selectedHeaderLabel}</h2>
          </div>
          <div className="tag-row">
            <span className="status-chip status-chip--mode">
              {mode === 'decision' ? '决策' : 'Todo'}
            </span>
            <span className="status-chip">{selectedMetaLabel}</span>
          </div>
        </div>

        <div className="home-appbar__controls">
          <div className="date-switcher" aria-label="日期切换">
            <button
              className="ghost-button"
              type="button"
              onClick={() => {
                setSelectedDate((current) => addDays(current, -1))
              }}
            >
              前一天
            </button>
            <button
              className="primary-button"
              type="button"
              onClick={() => {
                setSelectedDate(new Date())
              }}
            >
              今天
            </button>
            <button
              className="ghost-button"
              type="button"
              onClick={() => {
                setSelectedDate((current) => addDays(current, 1))
              }}
            >
              后一天
            </button>
          </div>

          <div className="weather-chip" aria-label="天气占位">
            <span className="weather-chip__icon">o</span>
            <span>天气</span>
          </div>
        </div>
      </section>

      <section className="mode-switcher-wrap">
        <div className="mode-switcher" role="tablist" aria-label="主页面模式切换">
          <button
            className={
              mode === 'decision'
                ? 'mode-switcher__button mode-switcher__button--active'
                : 'mode-switcher__button'
            }
            type="button"
            role="tab"
            aria-selected={mode === 'decision'}
            onClick={() => {
              setMode('decision')
            }}
          >
            决策
          </button>

          <button
            className={
              mode === 'todo'
                ? 'mode-switcher__button mode-switcher__button--active'
                : 'mode-switcher__button'
            }
            type="button"
            role="tab"
            aria-selected={mode === 'todo'}
            onClick={() => {
              setMode('todo')
            }}
          >
            Todo
          </button>
        </div>
      </section>

      <section className="home-main">
        {mode === 'decision' ? (
          <DecisionModePanel selectedDate={selectedDate} />
        ) : (
          <TodoModePanel selectedDate={selectedDate} />
        )}
      </section>

      <section className="home-layout__composer">
        <SurfaceCard title="决策库" description="需要时再展开。">
          <div className="composer-entry">
            <button
              className="primary-button composer-entry__button"
              type="button"
              onClick={() => {
                setShowComposer((current) => !current)
              }}
            >
              {showComposer ? '收起添加入口' : '添加模板'}
            </button>

            <button
              className="ghost-button"
              type="button"
              onClick={() => {
                setShowTemplateManager((current) => !current)
              }}
            >
              {showTemplateManager ? '收起模板管理' : '模板管理'}
            </button>
          </div>

          {showComposer ? (
            <div className="composer-panel">
              <CreateTaskTemplateForm />
            </div>
          ) : null}

          {showTemplateManager ? (
            <div className="composer-panel composer-panel--secondary">
              <TemplateManagerPanel />
            </div>
          ) : null}
        </SurfaceCard>
      </section>
    </div>
  )
}
