import { appDataRepository } from '@/db'
import type {
  AppData,
  DayPlanItem,
  RecurrenceRule,
  RecurringTaskInstance,
  SceneTag,
  TaskTemplate,
  TimeBlock,
  TimeBlockSource,
} from '@/types'

type AutoGeneratedSyncResult = {
  allItems: DayPlanItem[]
  dayItems: DayPlanItem[]
  nightItems: DayPlanItem[]
}

type TimeContextResolution = {
  timeBlock: TimeBlock
  timeBlockSource: TimeBlockSource
}

type AutoGeneratedCandidate = {
  template: TaskTemplate
  recurringInstance: RecurringTaskInstance | null
  timeContext: TimeContextResolution
}

const DAY_SCENE_NAMES = new Set(['上午', '下午', '白天'])
const NIGHT_SCENE_NAMES = new Set(['晚上', '夜间'])

const pad = (value: number) => String(value).padStart(2, '0')

const toDateString = (date: Date) =>
  `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`

const toWeekDateKey = (date: Date) => {
  const utcDate = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()))
  const dayOfWeek = utcDate.getUTCDay() || 7
  utcDate.setUTCDate(utcDate.getUTCDate() + 4 - dayOfWeek)

  const yearStart = new Date(Date.UTC(utcDate.getUTCFullYear(), 0, 1))
  const weekNumber = Math.ceil((((utcDate.getTime() - yearStart.getTime()) / 86400000) + 1) / 7)

  return `${utcDate.getUTCFullYear()}-W${pad(weekNumber)}`
}

const toDateKey = (date: Date, recurrence: Exclude<RecurrenceRule, 'none'>) => {
  switch (recurrence) {
    case 'daily':
      return toDateString(date)
    case 'weekly':
      return toWeekDateKey(date)
    case 'monthly':
      return `${date.getFullYear()}-${pad(date.getMonth() + 1)}`
    case 'yearly':
      return String(date.getFullYear())
  }
}

const parseDate = (dateString: string) => {
  const [year, month, day] = dateString.split('-').map(Number)

  return new Date(year, month - 1, day)
}

const matchesSelectedDate = (template: TaskTemplate, selectedDate: Date, selectedDateKey: string) => {
  if (!template.date) {
    return false
  }

  const templateDate = parseDate(template.date)

  if (template.recurrence === 'none') {
    return template.date === selectedDateKey
  }

  if (selectedDate < templateDate) {
    return false
  }

  switch (template.recurrence) {
    case 'daily':
      return true
    case 'weekly':
      return templateDate.getDay() === selectedDate.getDay()
    case 'monthly':
      return templateDate.getDate() === selectedDate.getDate()
    case 'yearly':
      return (
        templateDate.getMonth() === selectedDate.getMonth() &&
        templateDate.getDate() === selectedDate.getDate()
      )
  }
}

const resolveTimeContext = (sceneTagIds: string[], sceneTags: SceneTag[]): TimeContextResolution => {
  const sceneNames = sceneTags
    .filter((sceneTag) => sceneTagIds.includes(sceneTag.id))
    .map((sceneTag) => sceneTag.name)

  const hasNightTag = sceneNames.some((sceneName) => NIGHT_SCENE_NAMES.has(sceneName))

  if (hasNightTag) {
    return {
      timeBlock: 'night',
      timeBlockSource: 'mapped_night',
    }
  }

  const hasDayTag = sceneNames.some((sceneName) => DAY_SCENE_NAMES.has(sceneName))

  if (hasDayTag) {
    return {
      timeBlock: 'day',
      timeBlockSource: 'mapped_day',
    }
  }

  return {
    timeBlock: 'day',
    timeBlockSource: 'default_day',
  }
}

const hasConsumedTrigger = (
  appData: AppData,
  templateId: string,
  targetDate: string,
) =>
  appData.dayPlanItems.some(
    (item) =>
      item.templateId === templateId &&
      item.targetDate === targetDate &&
      item.consumesDateTrigger === true,
  )

const compareDateKeys = (left: string, right: string) => left.localeCompare(right)

const updateRecurringInstancesForTemplate = (
  appData: AppData,
  template: TaskTemplate,
  selectedDate: Date,
  nowIso: string,
) => {
  if (template.recurrence === 'none') {
    return {
      appData,
      recurringInstance: null,
    }
  }

  const currentDateKey = toDateKey(selectedDate, template.recurrence)
  const templateInstances = appData.recurringTaskInstances.filter(
    (instance) => instance.templateId === template.id && instance.recurrence === template.recurrence,
  )

  let updatedRecurringInstances = appData.recurringTaskInstances.map((instance) => {
    if (
      instance.templateId !== template.id ||
      instance.recurrence !== template.recurrence ||
      instance.status !== 'pending' ||
      compareDateKeys(instance.dateKey, currentDateKey) >= 0
    ) {
      return instance
    }

    return {
      ...instance,
      status: 'expired' as const,
    }
  })

  let recurringInstance =
    templateInstances.find((instance) => instance.dateKey === currentDateKey) ?? null

  if (!recurringInstance) {
    recurringInstance = {
      id: `recurring-instance-${template.id}-${currentDateKey}`,
      templateId: template.id,
      dateKey: currentDateKey,
      recurrence: template.recurrence,
      status: 'pending',
      progressState: 'not_started',
      progressPercent: 0,
      progressNote: '',
      generatedAt: nowIso,
    }

    updatedRecurringInstances = [...updatedRecurringInstances, recurringInstance]
  }

  return {
    appData: {
      ...appData,
      recurringTaskInstances: updatedRecurringInstances,
    },
    recurringInstance,
  }
}

const findExistingAutoGeneratedItem = (
  appData: AppData,
  templateId: string,
  targetDate: string,
) =>
  appData.dayPlanItems.find(
    (item) =>
      item.source === 'auto_generated' &&
      item.templateId === templateId &&
      item.targetDate === targetDate &&
      item.status !== 'deleted',
  )

const syncAutoGeneratedItem = (
  appData: AppData,
  candidate: AutoGeneratedCandidate,
  selectedDateKey: string,
  sortOrder: number,
  nowIso: string,
) => {
  const existingItem = findExistingAutoGeneratedItem(
    appData,
    candidate.template.id,
    selectedDateKey,
  )

  const baseItem = {
    date: selectedDateKey,
    targetDate: selectedDateKey,
    timeBlock: candidate.timeContext.timeBlock,
    timeBlockSource: candidate.timeContext.timeBlockSource,
    sortOrder,
    source: 'auto_generated' as const,
    templateId: candidate.template.id,
    recurringInstanceId: candidate.recurringInstance?.id,
    title: candidate.template.title,
    activityTypeId: candidate.template.activityTypeId,
    isNecessary: candidate.template.isNecessary,
    requiresPreparation: candidate.template.requiresPreparation,
    preparationNotes: candidate.template.preparationNotes,
    isSegmented: candidate.template.isSegmented,
  }

  if (existingItem) {
    const nextDayPlanItems = appData.dayPlanItems.map((item) =>
      item.id === existingItem.id
        ? {
            ...item,
            ...baseItem,
          }
        : item,
    )

    return {
      appData: {
        ...appData,
        dayPlanItems: nextDayPlanItems,
      },
      dayPlanItem: nextDayPlanItems.find((item) => item.id === existingItem.id)!,
    }
  }

  const dayPlanItem: DayPlanItem = {
    id: `day-plan-item-auto-${candidate.template.id}-${selectedDateKey}`,
    createdAt: nowIso,
    ...baseItem,
    progressState: candidate.recurringInstance?.progressState ?? 'not_started',
    progressPercent: candidate.recurringInstance?.progressPercent ?? 0,
    status: 'pending',
  }

  return {
    appData: {
      ...appData,
      dayPlanItems: [...appData.dayPlanItems, dayPlanItem],
    },
    dayPlanItem,
  }
}

const getAutoGeneratedTemplates = (appData: AppData, selectedDate: Date, selectedDateKey: string) =>
  appData.taskTemplates.filter((template) => {
    if (template.isArchived) {
      return false
    }

    if (!matchesSelectedDate(template, selectedDate, selectedDateKey)) {
      return false
    }

    if (template.isNecessary) {
      return true
    }

    if (template.recurrence !== 'none') {
      return true
    }

    return template.date === selectedDateKey
  })

const sortCandidates = (candidates: AutoGeneratedCandidate[]) =>
  [...candidates].sort((left, right) => {
    const leftWeight =
      left.timeContext.timeBlockSource === 'mapped_day'
        ? 1
        : left.timeContext.timeBlockSource === 'default_day'
          ? 2
          : 3

    const rightWeight =
      right.timeContext.timeBlockSource === 'mapped_day'
        ? 1
        : right.timeContext.timeBlockSource === 'default_day'
          ? 2
          : 3

    if (leftWeight !== rightWeight) {
      return leftWeight - rightWeight
    }

    return left.template.createdAt.localeCompare(right.template.createdAt)
  })

export async function syncAutoGeneratedDayPlanForDate(
  selectedDateInput: Date | string,
): Promise<AutoGeneratedSyncResult> {
  const selectedDate =
    typeof selectedDateInput === 'string'
      ? parseDate(selectedDateInput)
      : new Date(selectedDateInput)

  const selectedDateKey = toDateString(selectedDate)
  const nowIso = new Date().toISOString()

  const currentAppData = await appDataRepository.get()
  let nextAppData = currentAppData

  const candidates = getAutoGeneratedTemplates(currentAppData, selectedDate, selectedDateKey)
  const enrichedCandidates: AutoGeneratedCandidate[] = []

  for (const template of candidates) {
    if (hasConsumedTrigger(nextAppData, template.id, selectedDateKey)) {
      continue
    }

    const recurringResult = updateRecurringInstancesForTemplate(
      nextAppData,
      template,
      selectedDate,
      nowIso,
    )
    nextAppData = recurringResult.appData

    enrichedCandidates.push({
      template,
      recurringInstance: recurringResult.recurringInstance,
      timeContext: resolveTimeContext(template.sceneTagIds, currentAppData.sceneTags),
    })
  }

  const sortedCandidates = sortCandidates(enrichedCandidates)
  const syncedItems: DayPlanItem[] = []

  sortedCandidates.forEach((candidate, index) => {
    const syncResult = syncAutoGeneratedItem(
      nextAppData,
      candidate,
      selectedDateKey,
      index + 1,
      nowIso,
    )

    nextAppData = syncResult.appData
    syncedItems.push(syncResult.dayPlanItem)
  })

  const itemsToHide = nextAppData.dayPlanItems
    .filter(
      (item) =>
        item.source === 'auto_generated' &&
        item.targetDate === selectedDateKey &&
        !syncedItems.some((syncedItem) => syncedItem.id === item.id) &&
        item.status !== 'deleted',
    )
    .map((item) => item.id)

  if (itemsToHide.length > 0) {
    nextAppData = {
      ...nextAppData,
      dayPlanItems: nextAppData.dayPlanItems.map((item) =>
        itemsToHide.includes(item.id)
          ? {
              ...item,
              status: 'deleted',
            }
          : item,
      ),
    }
  }

  const appDataChanged = JSON.stringify(currentAppData) !== JSON.stringify(nextAppData)

  if (appDataChanged) {
    await appDataRepository.replace(nextAppData)
  }

  const visibleItems = nextAppData.dayPlanItems
    .filter(
      (item) =>
        item.source === 'auto_generated' &&
        item.targetDate === selectedDateKey &&
        item.status !== 'deleted',
    )
    .sort((left, right) => left.sortOrder - right.sortOrder)

  return {
    allItems: visibleItems,
    dayItems: visibleItems.filter((item) => item.timeBlock === 'day'),
    nightItems: visibleItems.filter((item) => item.timeBlock === 'night'),
  }
}
