import { appDataRepository } from '@/db'
import type {
  ActivityType,
  DayPlanItem,
  RecommendationResult,
  SceneTag,
  TaskTemplate,
  TieBreakerOrder,
  TimeBlock,
} from '@/types'

type RecommendationCandidate = {
  template: TaskTemplate
  matchedSceneTagIds: string[]
  usesEmptySceneTags: boolean
  alreadyUsedInOtherTimeBlock: boolean
}

type RecommendationContext = {
  selectedDate: Date
  timeBlock: TimeBlock
  activityTypeId: string
}

type RecommendationData = RecommendationResult & {
  sceneTagIds: string[]
}

const WEEKDAY_NAMES = new Set(['周中'])
const WEEKEND_NAMES = new Set(['周末'])
const DAY_CONTEXT_NAMES = new Set(['上午', '下午', '白天'])
const NIGHT_CONTEXT_NAMES = new Set(['晚上', '夜间'])

const pad = (value: number) => String(value).padStart(2, '0')

const toDateString = (date: Date) =>
  `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`

const deriveSceneTagIds = (
  sceneTags: SceneTag[],
  selectedDate: Date,
  timeBlock: TimeBlock,
) => {
  const isWeekend = [0, 6].includes(selectedDate.getDay())
  const matchedNames = new Set<string>()

  if (isWeekend) {
    WEEKEND_NAMES.forEach((name) => matchedNames.add(name))
  } else {
    WEEKDAY_NAMES.forEach((name) => matchedNames.add(name))
  }

  ;(timeBlock === 'day' ? DAY_CONTEXT_NAMES : NIGHT_CONTEXT_NAMES).forEach((name) =>
    matchedNames.add(name),
  )

  return sceneTags
    .filter((sceneTag) => matchedNames.has(sceneTag.name))
    .map((sceneTag) => sceneTag.id)
}

const compareByTieBreakerOrder = (
  left: TaskTemplate,
  right: TaskTemplate,
  tieBreakerOrder: TieBreakerOrder,
) =>
  tieBreakerOrder === 'asc'
    ? left.createdAt.localeCompare(right.createdAt)
    : right.createdAt.localeCompare(left.createdAt)

const sortCandidates = (
  candidates: RecommendationCandidate[],
  tieBreakerOrder: TieBreakerOrder,
) =>
  [...candidates].sort((left, right) => {
    if (left.alreadyUsedInOtherTimeBlock !== right.alreadyUsedInOtherTimeBlock) {
      return left.alreadyUsedInOtherTimeBlock ? 1 : -1
    }

    if (left.usesEmptySceneTags !== right.usesEmptySceneTags) {
      return left.usesEmptySceneTags ? 1 : -1
    }

    if (left.template.interestLevel !== right.template.interestLevel) {
      return right.template.interestLevel - left.template.interestLevel
    }

    return compareByTieBreakerOrder(left.template, right.template, tieBreakerOrder)
  })

export async function getDecisionRecommendations({
  selectedDate,
  timeBlock,
  activityTypeId,
}: RecommendationContext): Promise<RecommendationData> {
  const appData = await appDataRepository.get()
  const selectedDateKey = toDateString(selectedDate)
  const derivedSceneTagIds = deriveSceneTagIds(appData.sceneTags, selectedDate, timeBlock)

  const dayPlanItems = appData.dayPlanItems.filter(
    (item) => item.date === selectedDateKey && item.status !== 'deleted',
  )
  const autoGeneratedTemplateIds = new Set(
    dayPlanItems
      .filter((item) => item.source === 'auto_generated' && item.templateId)
      .map((item) => item.templateId as string),
  )
  const currentTimeBlockTemplateIds = new Set(
    dayPlanItems
      .filter((item) => item.timeBlock === timeBlock && item.templateId)
      .map((item) => item.templateId as string),
  )
  const otherTimeBlockTemplateIds = new Set(
    dayPlanItems
      .filter((item) => item.timeBlock !== timeBlock && item.templateId)
      .map((item) => item.templateId as string),
  )

  const candidates = appData.taskTemplates.reduce<RecommendationCandidate[]>((list, template) => {
    if (template.isArchived || template.isNecessary) {
      return list
    }

    if (template.activityTypeId !== activityTypeId) {
      return list
    }

    if (autoGeneratedTemplateIds.has(template.id)) {
      return list
    }

    if (currentTimeBlockTemplateIds.has(template.id)) {
      return list
    }

    const matchedSceneTagIds = template.sceneTagIds.filter((sceneTagId) =>
      derivedSceneTagIds.includes(sceneTagId),
    )
    const usesEmptySceneTags = template.sceneTagIds.length === 0

    if (!usesEmptySceneTags && matchedSceneTagIds.length === 0) {
      return list
    }

    list.push({
      template,
      matchedSceneTagIds,
      usesEmptySceneTags,
      alreadyUsedInOtherTimeBlock: otherTimeBlockTemplateIds.has(template.id),
    })

    return list
  }, [])

  const sortedCandidates = sortCandidates(candidates, appData.settings.tieBreakerOrder)
  const recommendedCandidate =
    sortedCandidates.find((candidate) => !candidate.alreadyUsedInOtherTimeBlock) ?? null

  return {
    recommended: recommendedCandidate?.template ?? null,
    candidates: sortedCandidates.map((candidate) => candidate.template),
    sceneTagIds: derivedSceneTagIds,
  }
}

export async function createDecisionSelectedDayPlanItem({
  selectedDate,
  timeBlock,
  template,
}: {
  selectedDate: Date
  timeBlock: TimeBlock
  template: TaskTemplate
}) {
  const appData = await appDataRepository.get()
  const selectedDateKey = toDateString(selectedDate)

  const existingItems = appData.dayPlanItems.filter(
    (item) =>
      item.date === selectedDateKey &&
      item.timeBlock === timeBlock &&
      item.status !== 'deleted',
  )

  if (existingItems.some((item) => item.templateId === template.id)) {
    throw new Error('当前时段已存在同一条种草，不能重复添加。')
  }

  const sortOrder =
    existingItems.length === 0
      ? 1
      : Math.max(...existingItems.map((item) => item.sortOrder)) + 1

  return appDataRepository.dayPlanItems.create({
    date: selectedDateKey,
    targetDate: template.date || undefined,
    timeBlock,
    timeBlockSource: timeBlock === 'night' ? 'manual_night' : 'default_day',
    sortOrder,
    source: 'decision_selected',
    templateId: template.id,
    title: template.title,
    activityTypeId: template.activityTypeId,
    isNecessary: template.isNecessary,
    requiresPreparation: template.requiresPreparation,
    preparationNotes: template.preparationNotes,
    isSegmented: template.isSegmented,
    progressState: 'not_started',
    progressPercent: 0,
    status: 'pending',
  })
}

export async function listDecisionActivityTypes(): Promise<ActivityType[]> {
  return appDataRepository.activityTypes.list()
}
