import { appDataRepository } from '@/db'
import { findLatestSegmentedTemplateCarryover } from '@/features/continuation'
import type {
  ActivityType,
  RecommendationResult,
  TaskTemplate,
  TieBreakerOrder,
  TimeBlock,
} from '@/types'

type RecommendationCandidate = {
  template: TaskTemplate
  matchedSceneTagIds: string[]
  alreadyUsedInOtherTimeBlock: boolean
}

type RecommendationContext = {
  selectedDate: Date
  timeBlock: TimeBlock
  activityTypeId: string
  sceneTagIds: string[]
}

type RecommendationData = RecommendationResult & {
  sceneTagIds: string[]
}

const pad = (value: number) => String(value).padStart(2, '0')

const toDateString = (date: Date) =>
  `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`

const compareByTieBreakerOrder = (
  left: TaskTemplate,
  right: TaskTemplate,
  tieBreakerOrder: TieBreakerOrder,
) =>
  tieBreakerOrder === 'asc'
    ? left.createdAt.localeCompare(right.createdAt)
    : right.createdAt.localeCompare(left.createdAt)

const sortCandidates = (
  candidates: RecommendationCandidate[],
  tieBreakerOrder: TieBreakerOrder,
) =>
  [...candidates].sort((left, right) => {
    if (left.alreadyUsedInOtherTimeBlock !== right.alreadyUsedInOtherTimeBlock) {
      return left.alreadyUsedInOtherTimeBlock ? 1 : -1
    }

    if (left.template.interestLevel !== right.template.interestLevel) {
      return right.template.interestLevel - left.template.interestLevel
    }

    return compareByTieBreakerOrder(left.template, right.template, tieBreakerOrder)
  })

export async function getDecisionRecommendations({
  selectedDate,
  timeBlock,
  activityTypeId,
  sceneTagIds,
}: RecommendationContext): Promise<RecommendationData> {
  const appData = await appDataRepository.get()
  const selectedDateKey = toDateString(selectedDate)

  const dayPlanItems = appData.dayPlanItems.filter(
    (item) => item.date === selectedDateKey && item.status !== 'deleted',
  )
  const autoGeneratedTemplateIds = new Set(
    dayPlanItems
      .filter((item) => item.source === 'auto_generated' && item.templateId)
      .map((item) => item.templateId as string),
  )
  const currentTimeBlockTemplateIds = new Set(
    dayPlanItems
      .filter((item) => item.timeBlock === timeBlock && item.templateId)
      .map((item) => item.templateId as string),
  )
  const otherTimeBlockTemplateIds = new Set(
    dayPlanItems
      .filter((item) => item.timeBlock !== timeBlock && item.templateId)
      .map((item) => item.templateId as string),
  )

  const candidates = appData.taskTemplates.reduce<RecommendationCandidate[]>((list, template) => {
    if (template.templateKind !== 'grass') {
      return list
    }

    if (template.grassStatus !== 'active' || template.isArchived) {
      return list
    }

    if (template.activityTypeId !== activityTypeId) {
      return list
    }

    if (autoGeneratedTemplateIds.has(template.id)) {
      return list
    }

    if (currentTimeBlockTemplateIds.has(template.id)) {
      return list
    }

    const matchedSceneTagIds = template.sceneTagIds.filter((sceneTagId) => sceneTagIds.includes(sceneTagId))
    if (sceneTagIds.length > 0 && matchedSceneTagIds.length === 0) {
      return list
    }

    list.push({
      template,
      matchedSceneTagIds,
      alreadyUsedInOtherTimeBlock: otherTimeBlockTemplateIds.has(template.id),
    })

    return list
  }, [])

  const sortedCandidates = sortCandidates(candidates, appData.settings.tieBreakerOrder)
  const recommendedCandidate =
    sortedCandidates.find((candidate) => !candidate.alreadyUsedInOtherTimeBlock) ?? null

  return {
    recommended: recommendedCandidate?.template ?? null,
    candidates: sortedCandidates.map((candidate) => candidate.template),
    sceneTagIds,
  }
}

type DecisionSelectedOptions = {
  isNecessary: boolean
  deadlineDate?: string
  requiresPreparation: boolean
  preparationNotes: string
  isSegmented: boolean
  isStepped: boolean
  currentStep: string
  nextStep: string
}

export async function createDecisionSelectedDayPlanItem({
  selectedDate,
  timeBlock,
  template,
  options,
}: {
  selectedDate: Date
  timeBlock: TimeBlock
  template: TaskTemplate
  options: DecisionSelectedOptions
}) {
  const appData = await appDataRepository.get()
  const selectedDateKey = toDateString(selectedDate)

  const existingItems = appData.dayPlanItems.filter(
    (item) =>
      item.date === selectedDateKey &&
      item.timeBlock === timeBlock &&
      item.status !== 'deleted',
  )

  if (existingItems.some((item) => item.templateId === template.id)) {
    throw new Error('当前时段已存在同一条种草，不能重复添加。')
  }

  const sortOrder =
    existingItems.length === 0
      ? 1
      : Math.max(...existingItems.map((item) => item.sortOrder)) + 1

  const carryover =
    options.isSegmented && template.id
      ? findLatestSegmentedTemplateCarryover({
          appData,
          templateId: template.id,
          beforeDate: selectedDate,
        })
      : null

  const createdItem = await appDataRepository.dayPlanItems.create({
    date: selectedDateKey,
    originDate: selectedDateKey,
    targetDate: template.date || undefined,
    timeBlock,
    timeBlockSource: timeBlock === 'night' ? 'manual_night' : 'default_day',
    sortOrder,
    source: 'decision_selected',
    templateId: template.id,
    title: template.title,
    activityTypeId: template.activityTypeId,
    isNecessary: options.isNecessary,
    deadlineDate: options.deadlineDate,
    requiresPreparation: options.requiresPreparation,
    preparationNotes: options.preparationNotes,
    isSegmented: options.isStepped ? false : options.isSegmented,
    isStepped: options.isStepped,
    currentStep: options.isStepped ? options.currentStep : '',
    nextStep: options.isStepped ? options.nextStep : '',
    progressState: carryover && carryover.progressPercent > 0 ? 'in_progress' : 'not_started',
    progressPercent: carryover?.progressPercent ?? 0,
    status: 'pending',
    rootItemId: carryover ? carryover.rootItemId ?? carryover.id : undefined,
    continuationOfItemId: carryover?.id,
    carriedFromDate: carryover?.date,
  })

  if (carryover) {
    await appDataRepository.taskTemplates.update({
      id: template.id,
      grassStatus: 'picked',
      isArchived: false,
    })

    return createdItem
  }

  const updatedItem = await appDataRepository.dayPlanItems.update({
    id: createdItem.id,
    rootItemId: createdItem.id,
    stepRootItemId: options.isStepped ? createdItem.id : undefined,
  })

  await appDataRepository.taskTemplates.update({
    id: template.id,
    grassStatus: 'picked',
    isArchived: false,
  })

  return updatedItem
}

export async function listDecisionActivityTypes(): Promise<ActivityType[]> {
  return appDataRepository.activityTypes.list()
}
