import { useEffect, useMemo, useState } from 'react'

import { appDataRepository } from '@/db'
import { syncAutoGeneratedDayPlanForDate } from '@/features/recurrence'
import type { DayPlanItem, DayPlanItemSource } from '@/types'

type TodoViewState = {
  isLoading: boolean
  errorMessage: string | null
  items: DayPlanItem[]
}

type NotesVisibilityMap = Record<string, boolean>
type TemporaryTimeBlock = 'day' | 'night'
type ProgressDraftMap = Record<string, number>
type ExpandedProgressMap = Record<string, boolean>

const pad = (value: number) => String(value).padStart(2, '0')

const toDateString = (date: Date) =>
  `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`

const sourceLabelMap: Record<DayPlanItemSource, string> = {
  auto_generated: '自动',
  decision_selected: '已选',
  manual_temporary: '临时',
}

function sortTodoItems(items: DayPlanItem[]) {
  return [...items].sort((left, right) => {
    if (left.timeBlock !== right.timeBlock) {
      return left.timeBlock === 'day' ? -1 : 1
    }

    if (left.sortOrder !== right.sortOrder) {
      return left.sortOrder - right.sortOrder
    }

    return left.createdAt.localeCompare(right.createdAt)
  })
}

function buildItemTags(item: DayPlanItem) {
  const tags = [sourceLabelMap[item.source]]

  if (item.isNecessary) {
    tags.push('必要')
  }

  if (item.isSegmented) {
    tags.push(`分次 ${item.progressPercent}%`)
  }

  if (item.requiresPreparation) {
    tags.push('准备')
  }

  if (item.status === 'completed') {
    tags.push('已完成')
  }

  return tags
}

export function TodoModePanel({ selectedDate }: { selectedDate: Date }) {
  const [viewState, setViewState] = useState<TodoViewState>({
    isLoading: true,
    errorMessage: null,
    items: [],
  })
  const [notesVisibility, setNotesVisibility] = useState<NotesVisibilityMap>({})
  const [temporaryTitle, setTemporaryTitle] = useState('')
  const [temporaryTimeBlock, setTemporaryTimeBlock] = useState<TemporaryTimeBlock>('day')
  const [progressDrafts, setProgressDrafts] = useState<ProgressDraftMap>({})
  const [expandedProgressItems, setExpandedProgressItems] = useState<ExpandedProgressMap>({})

  const selectedDateKey = useMemo(() => toDateString(selectedDate), [selectedDate])

  useEffect(() => {
    let cancelled = false

    const loadItems = async () => {
      setViewState((current) => ({
        ...current,
        isLoading: true,
        errorMessage: null,
      }))

      try {
        await syncAutoGeneratedDayPlanForDate(selectedDate)
        const appData = await appDataRepository.get()

        if (cancelled) {
          return
        }

        const items = sortTodoItems(
          appData.dayPlanItems.filter(
            (item) => item.date === selectedDateKey && item.status !== 'deleted',
          ),
        )

        setViewState({
          isLoading: false,
          errorMessage: null,
          items,
        })
      } catch (error: unknown) {
        if (cancelled) {
          return
        }

        setViewState({
          isLoading: false,
          errorMessage:
            error instanceof Error ? error.message : 'Todo 列表读取失败，请稍后重试。',
          items: [],
        })
      }
    }

    void loadItems()

    return () => {
      cancelled = true
    }
  }, [selectedDate, selectedDateKey])

  const dayItems = useMemo(
    () => viewState.items.filter((item) => item.timeBlock === 'day'),
    [viewState.items],
  )
  const nightItems = useMemo(
    () => viewState.items.filter((item) => item.timeBlock === 'night'),
    [viewState.items],
  )

  const toggleNotes = (itemId: string) => {
    setNotesVisibility((current) => ({
      ...current,
      [itemId]: !current[itemId],
    }))
  }

  const toggleProgressEditor = (item: DayPlanItem) => {
    if (!item.isSegmented || item.status === 'completed') {
      return
    }

    setExpandedProgressItems((current) => ({
      ...current,
      [item.id]: !current[item.id],
    }))
    setProgressDrafts((current) => ({
      ...current,
      [item.id]: current[item.id] ?? item.progressPercent,
    }))
  }

  const setProgressDraft = (itemId: string, nextValue: number) => {
    const normalized = Math.max(0, Math.min(100, Number.isNaN(nextValue) ? 0 : nextValue))

    setProgressDrafts((current) => ({
      ...current,
      [itemId]: normalized,
    }))
  }

  const reloadItems = async () => {
    const appData = await appDataRepository.get()

    setViewState((current) => ({
      ...current,
      items: sortTodoItems(
        appData.dayPlanItems.filter(
          (item) => item.date === selectedDateKey && item.status !== 'deleted',
        ),
      ),
    }))
  }

  const createTemporaryItem = async () => {
    const title = temporaryTitle.trim()

    if (!title) {
      return
    }

    const existingItemsInTimeBlock = viewState.items.filter(
      (item) => item.timeBlock === temporaryTimeBlock && item.status !== 'deleted',
    )
    const sortOrder =
      existingItemsInTimeBlock.length === 0
        ? 1
        : Math.max(...existingItemsInTimeBlock.map((item) => item.sortOrder)) + 1

    await appDataRepository.dayPlanItems.create({
      date: selectedDateKey,
      timeBlock: temporaryTimeBlock,
      timeBlockSource: temporaryTimeBlock === 'night' ? 'manual_night' : 'default_day',
      sortOrder,
      source: 'manual_temporary',
      title,
      isNecessary: false,
      requiresPreparation: false,
      preparationNotes: '',
      isSegmented: false,
      progressState: 'not_started',
      progressPercent: 0,
      status: 'pending',
    })

    setTemporaryTitle('')
    await reloadItems()
  }

  const saveSegmentedProgress = async (item: DayPlanItem) => {
    if (!item.isSegmented || item.status === 'completed' || item.source === 'manual_temporary') {
      return
    }

    const nextProgressPercent = Math.max(
      item.progressPercent,
      Math.min(100, progressDrafts[item.id] ?? item.progressPercent),
    )
    const nextProgressState =
      nextProgressPercent === 0
        ? 'not_started'
        : nextProgressPercent === 100
          ? 'completed'
          : 'in_progress'
    const nowIso = new Date().toISOString()
    const isCompleted = nextProgressPercent === 100

    await appDataRepository.dayPlanItems.update({
      id: item.id,
      progressPercent: nextProgressPercent,
      progressState: nextProgressState,
      status: isCompleted ? 'completed' : item.status,
      completedAt: isCompleted ? nowIso : item.completedAt,
      consumesDateTrigger:
        isCompleted && Boolean(item.templateId && item.targetDate)
          ? true
          : item.consumesDateTrigger,
    })

    if (item.recurringInstanceId) {
      await appDataRepository.recurringTaskInstances.update({
        id: item.recurringInstanceId,
        progressPercent: nextProgressPercent,
        progressState: nextProgressState,
        status: isCompleted ? 'completed' : undefined,
        completedAt: isCompleted ? nowIso : undefined,
      })
    }

    setExpandedProgressItems((current) => ({
      ...current,
      [item.id]: false,
    }))
    setProgressDrafts((current) => ({
      ...current,
      [item.id]: nextProgressPercent,
    }))

    await reloadItems()
  }

  const completeItem = async (item: DayPlanItem) => {
    if (item.isSegmented || item.status === 'completed') {
      return
    }

    const nowIso = new Date().toISOString()

    await appDataRepository.dayPlanItems.update({
      id: item.id,
      status: 'completed',
      completedAt: nowIso,
      progressState: 'completed',
      progressPercent: 100,
      consumesDateTrigger:
        item.source !== 'manual_temporary' && Boolean(item.templateId && item.targetDate)
          ? true
          : item.consumesDateTrigger,
    })

    await reloadItems()
  }

  const deleteTemporaryItem = async (item: DayPlanItem) => {
    if (item.source !== 'manual_temporary') {
      return
    }

    await appDataRepository.dayPlanItems.update({
      id: item.id,
      status: 'deleted',
    })

    await reloadItems()
  }

  const renderItems = (items: DayPlanItem[], timeBlock: 'day' | 'night') => {
    if (items.length === 0) {
      return (
        <article className="empty-state-card">
          <p>{timeBlock === 'day' ? '白天没有事项' : '晚上没有事项'}</p>
        </article>
      )
    }

    return (
      <div className="todo-list">
        {items.map((item) => {
          const tags = buildItemTags(item)

          return (
            <article
              key={item.id}
              className={
                item.timeBlock === 'day'
                  ? 'todo-item-card todo-item-card--day'
                  : 'todo-item-card todo-item-card--night'
              }
            >
              <div className="todo-item-card__header">
                <div className="todo-item-card__main">
                  <h5>{item.title}</h5>
                  <div className="tag-row">
                    {tags.map((tag) => (
                      <span
                        key={tag}
                        className={
                          tag === '必要'
                            ? 'status-chip status-chip--necessary'
                            : tag === '已完成'
                              ? 'status-chip status-chip--completed'
                              : 'status-chip'
                        }
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>

                <div className="todo-item-card__actions">
                  {item.source === 'manual_temporary' ? (
                    <button
                      className="ghost-button"
                      type="button"
                      onClick={() => {
                        void deleteTemporaryItem(item)
                      }}
                    >
                      删除
                    </button>
                  ) : null}

                  {item.isSegmented ? (
                    <button
                      className="ghost-button"
                      type="button"
                      disabled={item.status === 'completed' || item.source === 'manual_temporary'}
                      onClick={() => {
                        toggleProgressEditor(item)
                      }}
                    >
                      {item.status === 'completed'
                        ? '已完成'
                        : expandedProgressItems[item.id]
                          ? '收起'
                          : '推进'}
                    </button>
                  ) : (
                    <button
                      className="primary-button"
                      type="button"
                      disabled={item.status === 'completed'}
                      onClick={() => {
                        void completeItem(item)
                      }}
                    >
                      {item.status === 'completed' ? '已完成' : '完成'}
                    </button>
                  )}
                </div>
              </div>

              {item.isSegmented ? (
                <div className="segmented-progress-panel">
                  {item.source === 'manual_temporary' ? (
                    <p className="form-message">临时事项不支持分次推进。</p>
                  ) : item.status === 'completed' ? (
                    <p className="form-message form-message--success">已完成</p>
                  ) : expandedProgressItems[item.id] ? (
                    <>
                      <div className="segmented-progress-panel__controls">
                        <input
                          type="range"
                          min="0"
                          max="100"
                          value={progressDrafts[item.id] ?? item.progressPercent}
                          onChange={(event) => {
                            setProgressDraft(item.id, Number(event.target.value))
                          }}
                        />
                        <input
                          className="segmented-progress-panel__number"
                          type="number"
                          min="0"
                          max="100"
                          value={progressDrafts[item.id] ?? item.progressPercent}
                          onChange={(event) => {
                            setProgressDraft(item.id, Number(event.target.value))
                          }}
                        />
                      </div>

                      <div className="segmented-progress-panel__actions">
                        <span className="status-chip">
                          {progressDrafts[item.id] ?? item.progressPercent}%
                        </span>
                        <button
                          className="primary-button"
                          type="button"
                          onClick={() => {
                            void saveSegmentedProgress(item)
                          }}
                        >
                          保存进度
                        </button>
                      </div>
                    </>
                  ) : null}
                </div>
              ) : null}

              {item.requiresPreparation ? (
                <div className="todo-item-card__notes">
                  <button
                    className="ghost-button ghost-button--compact"
                    type="button"
                    onClick={() => {
                      toggleNotes(item.id)
                    }}
                  >
                    {notesVisibility[item.id] ? '收起准备' : '查看准备'}
                  </button>
                  {notesVisibility[item.id] ? (
                    <p>{item.preparationNotes || '暂无备注'}</p>
                  ) : null}
                </div>
              ) : null}
            </article>
          )
        })}
      </div>
    )
  }

  if (viewState.isLoading) {
    return (
      <div className="mode-panel">
        <div className="mode-panel__summary">
          <div>
            <p className="eyebrow">Todo</p>
            <h2>加载中</h2>
          </div>
        </div>
      </div>
    )
  }

  if (viewState.errorMessage) {
    return (
      <div className="mode-panel">
        <div className="empty-state-card empty-state-card--danger">
          <p>{viewState.errorMessage}</p>
        </div>
      </div>
    )
  }

  return (
    <div className="mode-panel">
      <div className="mode-panel__summary">
        <div>
          <p className="eyebrow">Todo</p>
          <h2>今天</h2>
        </div>
        <div className="tag-row">
          <span className="status-chip">{dayItems.length} 个白天</span>
          <span className="status-chip">{nightItems.length} 个晚上</span>
        </div>
      </div>

      <div className="temporary-composer temporary-composer--compact">
        <div className="temporary-composer__header">
          <div>
            <p className="eyebrow">Quick Add</p>
            <h4>临时事项</h4>
          </div>
        </div>

        <div className="temporary-composer__controls">
          <input
            className="temporary-composer__input"
            type="text"
            value={temporaryTitle}
            onChange={(event) => {
              setTemporaryTitle(event.target.value)
            }}
            onKeyDown={(event) => {
              if (event.key === 'Enter') {
                event.preventDefault()
                void createTemporaryItem()
              }
            }}
            placeholder="输入一条临时事项"
          />

          <select
            className="temporary-composer__select"
            value={temporaryTimeBlock}
            onChange={(event) => {
              setTemporaryTimeBlock(event.target.value as TemporaryTimeBlock)
            }}
          >
            <option value="day">白天</option>
            <option value="night">晚上</option>
          </select>

          <button
            className="primary-button"
            type="button"
            disabled={temporaryTitle.trim().length === 0}
            onClick={() => {
              void createTemporaryItem()
            }}
          >
            添加
          </button>
        </div>
      </div>

      <div className="todo-board">
        <section className="todo-board__section todo-board__section--day">
          <div className="todo-board__header">
            <p className="eyebrow">Day</p>
            <h4>白天</h4>
          </div>
          {renderItems(dayItems, 'day')}
        </section>

        <section className="todo-board__section todo-board__section--night">
          <div className="todo-board__header">
            <p className="eyebrow">Night</p>
            <h4>晚上</h4>
          </div>
          {renderItems(nightItems, 'night')}
        </section>
      </div>
    </div>
  )
}
