import { useEffect, useMemo, useState } from 'react'

import { MoonIcon, SunIcon } from '@/components/ui/Icons'
import { appDataRepository } from '@/db'
import {
  createDecisionSelectedDayPlanItem,
  getDecisionRecommendations,
  listDecisionActivityTypes,
} from '@/features/decision'
import { syncAutoGeneratedDayPlanForDate } from '@/features/recurrence'
import type {
  ActivityType,
  DayPlanItem,
  DayPlanItemSource,
  TaskTemplate,
  TimeBlock,
} from '@/types'

type TodoViewState = {
  isLoading: boolean
  errorMessage: string | null
  items: DayPlanItem[]
}

type RecommendationPanelState = {
  timeBlock: TimeBlock
  activityTypeId: string
  recommended: TaskTemplate | null
  candidates: TaskTemplate[]
  errorMessage: string | null
  isLoading: boolean
}

type NotesVisibilityMap = Record<string, boolean>
type TemporaryTimeBlock = 'day' | 'night'
type ProgressDraftMap = Record<string, number>
type ExpandedProgressMap = Record<string, boolean>

const pad = (value: number) => String(value).padStart(2, '0')

const toDateString = (date: Date) =>
  `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`

const sourceLabelMap: Record<DayPlanItemSource, string> = {
  auto_generated: '自动',
  decision_selected: '拔草',
  manual_temporary: '临时',
}

function sortTodoItems(items: DayPlanItem[]) {
  return [...items].sort((left, right) => {
    if (left.timeBlock !== right.timeBlock) {
      return left.timeBlock === 'day' ? -1 : 1
    }

    if (left.sortOrder !== right.sortOrder) {
      return left.sortOrder - right.sortOrder
    }

    return left.createdAt.localeCompare(right.createdAt)
  })
}

function buildItemTags(item: DayPlanItem) {
  const tags = [sourceLabelMap[item.source]]

  if (item.isNecessary) {
    tags.push('必要')
  }

  if (item.isSegmented) {
    tags.push(`分次 ${item.progressPercent}%`)
  }

  if (item.requiresPreparation) {
    tags.push('准备')
  }

  if (item.status === 'completed') {
    tags.push('已完成')
  }

  return tags
}

function RecommendationInlineCard({
  activityTypes,
  panelState,
  onActivityTypeChange,
  onConfirm,
  onClose,
}: {
  activityTypes: ActivityType[]
  panelState: RecommendationPanelState
  onActivityTypeChange: (activityTypeId: string) => void
  onConfirm: (template: TaskTemplate) => void
  onClose: () => void
}) {
  const visibleCandidates = panelState.candidates

  return (
    <div className="recommendation-card">
      <div className="recommendation-card__header">
        <span className="status-chip recommendation-card__context">
          {panelState.timeBlock === 'day' ? '白天' : '晚上'}
        </span>
        <button className="ghost-button" type="button" onClick={onClose}>
          收起
        </button>
      </div>

      <label className="editor-field">
        <span>种草清单</span>
        <select
          value={panelState.activityTypeId}
          onChange={(event) => {
            onActivityTypeChange(event.target.value)
          }}
        >
          {activityTypes.map((activityType) => (
            <option key={activityType.id} value={activityType.id}>
              {activityType.name}
            </option>
          ))}
        </select>
      </label>

      {panelState.isLoading ? (
        <p className="form-message">正在加载候选...</p>
      ) : panelState.errorMessage ? (
        <p className="form-message form-message--danger">{panelState.errorMessage}</p>
      ) : (
        <div className="recommendation-card__body">
          {visibleCandidates.length === 0 ? (
            <div className="empty-state-card">
              <p>没有可选候选</p>
            </div>
          ) : (
            <div className="candidate-list">
              {visibleCandidates.map((candidate) => {
                const isRecommended = panelState.recommended?.id === candidate.id

                return (
                  <article
                    className={
                      isRecommended
                        ? 'candidate-item candidate-item--recommended'
                        : 'candidate-item'
                    }
                    key={candidate.id}
                  >
                    <div className="candidate-item__main">
                      <h6>{candidate.title}</h6>
                      <div className="tag-row">
                        {isRecommended ? <span className="status-chip">默认推荐</span> : null}
                        <span className="status-chip">兴趣 {candidate.interestLevel}</span>
                        {candidate.date ? (
                          <span className="status-chip">{candidate.date}</span>
                        ) : null}
                      </div>
                    </div>
                    <button
                      className={isRecommended ? 'primary-button' : 'ghost-button'}
                      type="button"
                      onClick={() => {
                        onConfirm(candidate)
                      }}
                    >
                      添加
                    </button>
                  </article>
                )
              })}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

export function TodoModePanel({ selectedDate }: { selectedDate: Date }) {
  const [viewState, setViewState] = useState<TodoViewState>({
    isLoading: true,
    errorMessage: null,
    items: [],
  })
  const [notesVisibility, setNotesVisibility] = useState<NotesVisibilityMap>({})
  const [temporaryTitle, setTemporaryTitle] = useState('')
  const [temporaryTimeBlock, setTemporaryTimeBlock] = useState<TemporaryTimeBlock>('day')
  const [showMoreOptions, setShowMoreOptions] = useState(false)
  const [activityTypes, setActivityTypes] = useState<ActivityType[]>([])
  const [composerErrorMessage, setComposerErrorMessage] = useState<string | null>(null)
  const [isNecessaryDraft, setIsNecessaryDraft] = useState(false)
  const [requiresPreparationDraft, setRequiresPreparationDraft] = useState(false)
  const [preparationNotesDraft, setPreparationNotesDraft] = useState('')
  const [isSegmentedDraft, setIsSegmentedDraft] = useState(false)
  const [recommendationPanel, setRecommendationPanel] = useState<RecommendationPanelState | null>(null)
  const [progressDrafts, setProgressDrafts] = useState<ProgressDraftMap>({})
  const [expandedProgressItems, setExpandedProgressItems] = useState<ExpandedProgressMap>({})

  const selectedDateKey = useMemo(() => toDateString(selectedDate), [selectedDate])

  useEffect(() => {
    let cancelled = false

    const loadItems = async () => {
      setViewState((current) => ({
        ...current,
        isLoading: true,
        errorMessage: null,
      }))

      try {
        await syncAutoGeneratedDayPlanForDate(selectedDate)
        const appData = await appDataRepository.get()

        if (cancelled) {
          return
        }

        const items = sortTodoItems(
          appData.dayPlanItems.filter(
            (item) => item.date === selectedDateKey && item.status !== 'deleted',
          ),
        )

        setViewState({
          isLoading: false,
          errorMessage: null,
          items,
        })
      } catch (error: unknown) {
        if (cancelled) {
          return
        }

        setViewState({
          isLoading: false,
          errorMessage:
            error instanceof Error ? error.message : 'Todo 列表读取失败，请稍后重试。',
          items: [],
        })
      }
    }

    void loadItems()

    return () => {
      cancelled = true
    }
  }, [selectedDate, selectedDateKey])

  useEffect(() => {
    if (!showMoreOptions) {
      setRecommendationPanel(null)
    }
  }, [showMoreOptions])

  const dayItems = useMemo(
    () => viewState.items.filter((item) => item.timeBlock === 'day'),
    [viewState.items],
  )
  const nightItems = useMemo(
    () => viewState.items.filter((item) => item.timeBlock === 'night'),
    [viewState.items],
  )

  const resetExpandedComposerState = () => {
    setShowMoreOptions(false)
    setIsNecessaryDraft(false)
    setRequiresPreparationDraft(false)
    setPreparationNotesDraft('')
    setIsSegmentedDraft(false)
    setRecommendationPanel(null)
  }

  const toggleNotes = (itemId: string) => {
    setNotesVisibility((current) => ({
      ...current,
      [itemId]: !current[itemId],
    }))
  }

  const toggleProgressEditor = (item: DayPlanItem) => {
    if (!item.isSegmented || item.status === 'completed') {
      return
    }

    setExpandedProgressItems((current) => ({
      ...current,
      [item.id]: !current[item.id],
    }))
    setProgressDrafts((current) => ({
      ...current,
      [item.id]: current[item.id] ?? item.progressPercent,
    }))
  }

  const setProgressDraft = (itemId: string, nextValue: number) => {
    const normalized = Math.max(0, Math.min(100, Number.isNaN(nextValue) ? 0 : nextValue))

    setProgressDrafts((current) => ({
      ...current,
      [itemId]: normalized,
    }))
  }

  const reloadItems = async () => {
    const appData = await appDataRepository.get()

    setViewState((current) => ({
      ...current,
      items: sortTodoItems(
        appData.dayPlanItems.filter(
          (item) => item.date === selectedDateKey && item.status !== 'deleted',
        ),
      ),
    }))
  }

  const createTemporaryItem = async () => {
    const title = temporaryTitle.trim()

    if (!title) {
      return
    }

    try {
      const existingItemsInTimeBlock = viewState.items.filter(
        (item) => item.timeBlock === temporaryTimeBlock && item.status !== 'deleted',
      )
      const sortOrder =
        existingItemsInTimeBlock.length === 0
          ? 1
          : Math.max(...existingItemsInTimeBlock.map((item) => item.sortOrder)) + 1

      await appDataRepository.dayPlanItems.create({
        date: selectedDateKey,
        timeBlock: temporaryTimeBlock,
        timeBlockSource: temporaryTimeBlock === 'night' ? 'manual_night' : 'default_day',
        sortOrder,
        source: 'manual_temporary',
        title,
        isNecessary: isNecessaryDraft,
        requiresPreparation: requiresPreparationDraft,
        preparationNotes: requiresPreparationDraft ? preparationNotesDraft.trim() : '',
        isSegmented: isSegmentedDraft,
        progressState: 'not_started',
        progressPercent: 0,
        status: 'pending',
      })

      setTemporaryTitle('')
      setComposerErrorMessage(null)
      resetExpandedComposerState()
      await reloadItems()
    } catch (error: unknown) {
      setComposerErrorMessage(
        error instanceof Error ? error.message : 'Todo 创建失败，请稍后重试。',
      )
    }
  }

  const loadRecommendationPanel = async ({
    timeBlock,
    activityTypeId,
  }: {
    timeBlock: TimeBlock
    activityTypeId: string
  }) => {
    const recommendation = await getDecisionRecommendations({
      selectedDate,
      timeBlock,
      activityTypeId,
    })

    setRecommendationPanel({
      timeBlock,
      activityTypeId,
      recommended: recommendation.recommended,
      candidates: recommendation.candidates,
      errorMessage: null,
      isLoading: false,
    })
  }

  const openRecommendationPanel = async () => {
    try {
      let nextActivityTypes = activityTypes

      if (nextActivityTypes.length === 0) {
        nextActivityTypes = await listDecisionActivityTypes()
        setActivityTypes(nextActivityTypes)
      }

      const defaultActivityTypeId = nextActivityTypes[0]?.id

      if (!defaultActivityTypeId) {
        setComposerErrorMessage('当前还没有可用的种草清单。')
        return
      }

      setComposerErrorMessage(null)
      setRecommendationPanel({
        timeBlock: temporaryTimeBlock,
        activityTypeId: defaultActivityTypeId,
        recommended: null,
        candidates: [],
        errorMessage: null,
        isLoading: true,
      })

      await loadRecommendationPanel({
        timeBlock: temporaryTimeBlock,
        activityTypeId: defaultActivityTypeId,
      })
    } catch (error: unknown) {
      setRecommendationPanel({
        timeBlock: temporaryTimeBlock,
        activityTypeId: activityTypes[0]?.id ?? '',
        recommended: null,
        candidates: [],
        errorMessage:
          error instanceof Error ? error.message : '拔草候选读取失败，请稍后重试。',
        isLoading: false,
      })
    }
  }

  const changeRecommendationActivityType = async (activityTypeId: string) => {
    if (!recommendationPanel) {
      return
    }

    setRecommendationPanel({
      ...recommendationPanel,
      activityTypeId,
      isLoading: true,
      errorMessage: null,
    })

    try {
      await loadRecommendationPanel({
        timeBlock: temporaryTimeBlock,
        activityTypeId,
      })
    } catch (error: unknown) {
      setRecommendationPanel({
        timeBlock: temporaryTimeBlock,
        activityTypeId,
        recommended: null,
        candidates: [],
        errorMessage:
          error instanceof Error ? error.message : '拔草候选读取失败，请稍后重试。',
        isLoading: false,
      })
    }
  }

  const addFromTemplate = async (template: TaskTemplate) => {
    try {
      await createDecisionSelectedDayPlanItem({
        selectedDate,
        timeBlock: temporaryTimeBlock,
        template,
      })

      setComposerErrorMessage(null)
      setRecommendationPanel(null)
      await reloadItems()
    } catch (error: unknown) {
      setComposerErrorMessage(
        error instanceof Error ? error.message : '从种草添加失败，请稍后重试。',
      )
    }
  }

  const saveSegmentedProgress = async (item: DayPlanItem) => {
    if (!item.isSegmented || item.status === 'completed' || item.source === 'manual_temporary') {
      return
    }

    const nextProgressPercent = Math.max(
      item.progressPercent,
      Math.min(100, progressDrafts[item.id] ?? item.progressPercent),
    )
    const nextProgressState =
      nextProgressPercent === 0
        ? 'not_started'
        : nextProgressPercent === 100
          ? 'completed'
          : 'in_progress'
    const nowIso = new Date().toISOString()
    const isCompleted = nextProgressPercent === 100

    await appDataRepository.dayPlanItems.update({
      id: item.id,
      progressPercent: nextProgressPercent,
      progressState: nextProgressState,
      status: isCompleted ? 'completed' : item.status,
      completedAt: isCompleted ? nowIso : item.completedAt,
      consumesDateTrigger:
        isCompleted && Boolean(item.templateId && item.targetDate)
          ? true
          : item.consumesDateTrigger,
    })

    if (item.recurringInstanceId) {
      await appDataRepository.recurringTaskInstances.update({
        id: item.recurringInstanceId,
        progressPercent: nextProgressPercent,
        progressState: nextProgressState,
        status: isCompleted ? 'completed' : undefined,
        completedAt: isCompleted ? nowIso : undefined,
      })
    }

    setExpandedProgressItems((current) => ({
      ...current,
      [item.id]: false,
    }))
    setProgressDrafts((current) => ({
      ...current,
      [item.id]: nextProgressPercent,
    }))

    await reloadItems()
  }

  const completeItem = async (item: DayPlanItem) => {
    if (item.isSegmented || item.status === 'completed') {
      return
    }

    const nowIso = new Date().toISOString()

    await appDataRepository.dayPlanItems.update({
      id: item.id,
      status: 'completed',
      completedAt: nowIso,
      progressState: 'completed',
      progressPercent: 100,
      consumesDateTrigger:
        item.source !== 'manual_temporary' && Boolean(item.templateId && item.targetDate)
          ? true
          : item.consumesDateTrigger,
    })

    await reloadItems()
  }

  const deleteTemporaryItem = async (item: DayPlanItem) => {
    if (item.source !== 'manual_temporary') {
      return
    }

    await appDataRepository.dayPlanItems.update({
      id: item.id,
      status: 'deleted',
    })

    await reloadItems()
  }

  const renderItems = (items: DayPlanItem[], timeBlock: 'day' | 'night') => {
    if (items.length === 0) {
      return (
        <article className="empty-state-card">
          <p>{timeBlock === 'day' ? '白天没有事项' : '晚上没有事项'}</p>
        </article>
      )
    }

    return (
      <div className="list-group__items">
        {items.map((item) => {
          const tags = buildItemTags(item)

          return (
            <article
              key={item.id}
              className={
                item.timeBlock === 'day'
                  ? 'todo-item-card todo-item-card--day'
                  : 'todo-item-card todo-item-card--night'
              }
            >
              <div className="todo-item-card__layout">
                <div className="todo-item-card__content">
                  <div className="todo-item-card__main">
                    <h5>{item.title}</h5>
                    <div className="tag-row">
                      {tags.map((tag) => (
                        <span
                          key={tag}
                          className={
                            tag === '必要'
                              ? 'status-chip status-chip--necessary'
                              : tag === '已完成'
                                ? 'status-chip status-chip--completed'
                                : 'status-chip'
                          }
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>

                  {item.requiresPreparation ? (
                    <div className="todo-item-card__notes">
                      <button
                        className="ghost-button ghost-button--compact"
                        type="button"
                        onClick={() => {
                          toggleNotes(item.id)
                        }}
                      >
                        {notesVisibility[item.id] ? '收起准备' : '查看准备'}
                      </button>
                      {notesVisibility[item.id] ? (
                        <p>{item.preparationNotes || '暂无备注'}</p>
                      ) : null}
                    </div>
                  ) : null}

                  {item.isSegmented && item.status !== 'completed' && item.source !== 'manual_temporary' ? (
                    <div className="todo-item-card__meta">
                      {!expandedProgressItems[item.id] ? (
                        <button
                          className="ghost-button ghost-button--compact"
                          type="button"
                          onClick={() => {
                            toggleProgressEditor(item)
                          }}
                        >
                          推进
                        </button>
                      ) : null}
                    </div>
                  ) : null}
                </div>

                <div className="todo-item-card__actions">
                  <button
                    className={
                      item.status === 'completed'
                        ? 'todo-check todo-check--checked'
                        : 'todo-check'
                    }
                    type="button"
                    aria-label={item.status === 'completed' ? '已完成' : '标记完成'}
                    disabled={item.status === 'completed' || item.isSegmented}
                    onClick={() => {
                      void completeItem(item)
                    }}
                  >
                    <span className="todo-check__mark" aria-hidden="true">
                      {item.status === 'completed' ? '✓' : ''}
                    </span>
                  </button>

                  <button
                    className="todo-item-card__delete"
                    type="button"
                    aria-label="删除事项"
                    onClick={() => {
                      void deleteTemporaryItem(item)
                    }}
                    disabled={item.source !== 'manual_temporary'}
                  >
                    ×
                  </button>
                </div>
              </div>

              {item.isSegmented ? (
                <div className="segmented-progress-panel">
                  {item.source === 'manual_temporary' ? (
                    <p className="form-message">临时事项不支持分次推进。</p>
                  ) : item.status === 'completed' ? (
                    <p className="form-message form-message--success">已完成</p>
                  ) : expandedProgressItems[item.id] ? (
                    <>
                      <div className="segmented-progress-panel__controls">
                        <input
                          type="range"
                          min="0"
                          max="100"
                          value={progressDrafts[item.id] ?? item.progressPercent}
                          onChange={(event) => {
                            setProgressDraft(item.id, Number(event.target.value))
                          }}
                        />
                        <input
                          className="segmented-progress-panel__number"
                          type="number"
                          min="0"
                          max="100"
                          value={progressDrafts[item.id] ?? item.progressPercent}
                          onChange={(event) => {
                            setProgressDraft(item.id, Number(event.target.value))
                          }}
                        />
                      </div>

                      <div className="segmented-progress-panel__actions">
                        <span className="status-chip">
                          {progressDrafts[item.id] ?? item.progressPercent}%
                        </span>
                        <button
                          className="primary-button"
                          type="button"
                          onClick={() => {
                            void saveSegmentedProgress(item)
                          }}
                        >
                          保存进度
                        </button>
                      </div>
                    </>
                  ) : null}
                </div>
              ) : null}

            </article>
          )
        })}
      </div>
    )
  }

  if (viewState.isLoading) {
    return (
      <div className="mode-panel">
        <div className="mode-panel__summary">
          <div>
            <p className="eyebrow">Todo</p>
            <h2>加载中</h2>
          </div>
        </div>
      </div>
    )
  }

  if (viewState.errorMessage) {
    return (
      <div className="mode-panel">
        <div className="empty-state-card empty-state-card--danger">
          <p>{viewState.errorMessage}</p>
        </div>
      </div>
    )
  }

  return (
    <div className="mode-panel">
      <div className="temporary-composer temporary-composer--compact">
        <div className="temporary-composer__controls temporary-composer__controls--expanded">
          <input
            className="temporary-composer__input"
            type="text"
            value={temporaryTitle}
            onChange={(event) => {
              setTemporaryTitle(event.target.value)
            }}
            onKeyDown={(event) => {
              if (event.key === 'Enter') {
                event.preventDefault()
                void createTemporaryItem()
              }
            }}
            placeholder="输入一条 Todo"
          />

          <div className="segmented-control temporary-composer__segmented" aria-label="Todo 时段">
            <button
              className={
                temporaryTimeBlock === 'day'
                  ? 'segmented-control__button segmented-control__button--active'
                  : 'segmented-control__button'
              }
              type="button"
              onClick={() => {
                setTemporaryTimeBlock('day')
              }}
              aria-label="白天"
            >
              <SunIcon className="segmented-control__icon" />
            </button>
            <button
              className={
                temporaryTimeBlock === 'night'
                  ? 'segmented-control__button segmented-control__button--active'
                  : 'segmented-control__button'
              }
              type="button"
              onClick={() => {
                setTemporaryTimeBlock('night')
              }}
              aria-label="晚上"
            >
              <MoonIcon className="segmented-control__icon" />
            </button>
          </div>

          <button
            className="ghost-button ghost-button--compact temporary-composer__more-toggle"
            type="button"
            onClick={() => {
              setComposerErrorMessage(null)

              if (showMoreOptions) {
                resetExpandedComposerState()
              } else {
                setShowMoreOptions(true)
              }
            }}
          >
            {showMoreOptions ? '收起' : '更多'}
          </button>

          <button
            className="primary-button"
            type="button"
            disabled={temporaryTitle.trim().length === 0}
            onClick={() => {
              void createTemporaryItem()
            }}
          >
            +
          </button>
        </div>

        {showMoreOptions ? (
          <div className="temporary-composer__more">
            <div className="temporary-composer__section">
              <div className="temporary-composer__action-row">
                <button
                  className="ghost-button"
                  type="button"
                  onClick={() => {
                    void openRecommendationPanel()
                  }}
                >
                  {recommendationPanel ? '刷新拔草推荐' : '打开拔草推荐'}
                </button>
              </div>

              {recommendationPanel ? (
                <RecommendationInlineCard
                  activityTypes={activityTypes}
                  panelState={recommendationPanel}
                  onActivityTypeChange={(activityTypeId) => {
                    void changeRecommendationActivityType(activityTypeId)
                  }}
                  onConfirm={(template) => {
                    void addFromTemplate(template)
                  }}
                  onClose={() => {
                    setRecommendationPanel(null)
                  }}
                />
              ) : (
                <div className="temporary-composer__hint-row">
                  <span className="status-chip">需要时再从种草里挑一条</span>
                </div>
              )}
            </div>

            <div className="temporary-composer__section">
              <label className="toggle-chip">
                <input
                  type="checkbox"
                  checked={isNecessaryDraft}
                  onChange={(event) => {
                    setIsNecessaryDraft(event.target.checked)
                  }}
                />
                <span>必要事项</span>
              </label>

              <label className="toggle-chip">
                <input
                  type="checkbox"
                  checked={requiresPreparationDraft}
                  onChange={(event) => {
                    const nextChecked = event.target.checked
                    setRequiresPreparationDraft(nextChecked)

                    if (!nextChecked) {
                      setPreparationNotesDraft('')
                    }
                  }}
                />
                <span>需要准备</span>
              </label>

              {requiresPreparationDraft ? (
                <textarea
                  className="template-form__notes-input"
                  rows={2}
                  value={preparationNotesDraft}
                  onChange={(event) => {
                    setPreparationNotesDraft(event.target.value)
                  }}
                  placeholder="记录这次 Todo 的准备备注"
                />
              ) : null}

              <label className="toggle-chip">
                <input
                  type="checkbox"
                  checked={isSegmentedDraft}
                  onChange={(event) => {
                    setIsSegmentedDraft(event.target.checked)
                  }}
                />
                <span>分次事项</span>
              </label>
            </div>
          </div>
        ) : null}

        {composerErrorMessage ? (
          <p className="form-message form-message--danger">{composerErrorMessage}</p>
        ) : null}
      </div>

      <div className="todo-board">
        <section className="list-group" aria-label="白天事项">
          <div className="list-group__header">
            <div className="list-group__heading">
              <p className="eyebrow">白天</p>
            </div>
          </div>
          <div className="list-group__divider" aria-hidden="true" />
          {renderItems(dayItems, 'day')}
        </section>

        <section className="list-group" aria-label="晚上事项">
          <div className="list-group__header">
            <div className="list-group__heading">
              <p className="eyebrow">晚上</p>
            </div>
          </div>
          <div className="list-group__divider" aria-hidden="true" />
          {renderItems(nightItems, 'night')}
        </section>
      </div>
    </div>
  )
}
