import type { DayPlanItem, RecurringTaskInstance, TaskTemplate, TimeBlock } from '@/types'

export type TodoOriginLabel = '手动' | '种草' | '重复' | '自动'

export type TodoInternalRef = {
  item: DayPlanItem
  template?: TaskTemplate
  recurringInstance?: RecurringTaskInstance
  templateKind?: TaskTemplate['templateKind']
}

export type TodoViewModel = {
  id: string
  title: string
  date: string
  timeBlock: TimeBlock
  isCompleted: boolean
  isDeleted: boolean
  isSegmented: boolean
  progressPercent: number
  isRepeating: boolean
  isNecessary: boolean
  preparationNotes: string
  createdAtHint: string
  originLabel: TodoOriginLabel
  canEdit: boolean
  canDelete: boolean
  canComplete: boolean
  canUncomplete: boolean
  canStopRepeating: boolean
  recurringToggleLabel: string
  isRecurringStopped: boolean
  internalRef: TodoInternalRef
}

type TodoMappingContext = {
  recurringInstancesById?: Record<string, RecurringTaskInstance>
  templateKindsById?: Record<string, TaskTemplate['templateKind']>
  templatesById?: Record<string, TaskTemplate>
}

const toMonthDayLabel = (dateString: string) => {
  const [, month, day] = dateString.split('-')

  return `${Number(month)}/${Number(day)}`
}

export function getOriginDate(item: DayPlanItem) {
  return item.originDate ?? item.targetDate ?? item.date
}

export function isRepeatingTodo(
  item: DayPlanItem,
  templateKind?: TaskTemplate['templateKind'],
) {
  return Boolean(item.recurringInstanceId || templateKind === 'todo_recurring')
}

export function getCreatedAtHint(item: DayPlanItem) {
  const originDate = getOriginDate(item)

  if (!originDate || originDate === item.date) {
    return ''
  }

  return `创建于 ${toMonthDayLabel(originDate)}`
}

export function getOriginLabel(
  item: DayPlanItem,
  templateKind?: TaskTemplate['templateKind'],
): TodoOriginLabel {
  if (isRepeatingTodo(item, templateKind)) {
    return '重复'
  }

  if (item.source === 'manual_temporary') {
    return '手动'
  }

  if (item.source === 'decision_selected') {
    return '种草'
  }

  return '自动'
}

export function getTodoCapabilities(
  item: DayPlanItem,
  templateKind?: TaskTemplate['templateKind'],
  template?: TaskTemplate,
) {
  const isTodoRecurring = templateKind === 'todo_recurring'
  const isRepeating = isRepeatingTodo(item, templateKind)
  const isRecurringAutoGenerated = item.source === 'auto_generated' && isRepeating
  const isCarriedOrdinaryAutoGenerated =
    item.source === 'auto_generated' && !isRepeating && getOriginDate(item) !== item.date
  const isCurrentHitOccurrence = getOriginDate(item) === item.date
  const isEditable =
    item.source === 'manual_temporary' ||
    item.source === 'decision_selected' ||
    isCarriedOrdinaryAutoGenerated
  const isDeletable =
    item.source === 'manual_temporary' ||
    item.source === 'decision_selected' ||
    isRecurringAutoGenerated ||
    isCarriedOrdinaryAutoGenerated
  const canStopRepeating =
    item.source === 'auto_generated' && isTodoRecurring && isCurrentHitOccurrence
  const canComplete = !item.isSegmented && item.status !== 'completed'
  const canUncomplete =
    !item.isSegmented &&
    item.status === 'completed' &&
    (item.source !== 'auto_generated' || isTodoRecurring || isCarriedOrdinaryAutoGenerated)
  const isRecurringStopped = Boolean(canStopRepeating && template?.isArchived)

  return {
    canEdit: isEditable,
    canDelete: isDeletable,
    canComplete,
    canUncomplete,
    canStopRepeating,
    recurringToggleLabel: isRecurringStopped ? '重复已停止' : '停止重复',
    isRecurringStopped,
  }
}

export function mapDayPlanItemToTodoViewModel(
  item: DayPlanItem,
  context: TodoMappingContext = {},
): TodoViewModel {
  const templateKind = item.templateId ? context.templateKindsById?.[item.templateId] : undefined
  const template = item.templateId ? context.templatesById?.[item.templateId] : undefined
  const recurringInstance = item.recurringInstanceId
    ? context.recurringInstancesById?.[item.recurringInstanceId]
    : undefined
  const capabilities = getTodoCapabilities(item, templateKind, template)

  return {
    id: item.id,
    title: item.title,
    date: item.date,
    timeBlock: item.timeBlock,
    isCompleted: item.status === 'completed',
    isDeleted: item.status === 'deleted',
    isSegmented: item.isSegmented,
    progressPercent: item.progressPercent,
    isRepeating: isRepeatingTodo(item, templateKind),
    isNecessary: item.isNecessary,
    preparationNotes:
      item.requiresPreparation && item.preparationNotes.trim() ? item.preparationNotes : '',
    createdAtHint: getCreatedAtHint(item),
    originLabel: getOriginLabel(item, templateKind),
    ...capabilities,
    internalRef: {
      item,
      template,
      recurringInstance,
      templateKind,
    },
  }
}

export function mapDayPlanItemsToTodoViewModels(
  items: DayPlanItem[],
  context: TodoMappingContext = {},
) {
  return items.map((item) => mapDayPlanItemToTodoViewModel(item, context))
}

export function buildTemplateKindMap(templates: TaskTemplate[]) {
  return templates.reduce<Record<string, TaskTemplate['templateKind']>>((map, template) => {
    map[template.id] = template.templateKind
    return map
  }, {})
}

export function buildTemplatesById(templates: TaskTemplate[]) {
  return templates.reduce<Record<string, TaskTemplate>>((map, template) => {
    map[template.id] = template
    return map
  }, {})
}

export function buildRecurringInstancesById(instances: RecurringTaskInstance[]) {
  return instances.reduce<Record<string, RecurringTaskInstance>>((map, instance) => {
    map[instance.id] = instance
    return map
  }, {})
}

export function buildTodoTags(viewModel: TodoViewModel) {
  const tags: string[] = [viewModel.originLabel]

  if (viewModel.isNecessary) {
    tags.push('必要')
  }

  if (viewModel.isSegmented) {
    tags.push(`分次 ${viewModel.progressPercent}%`)
  }

  if (viewModel.preparationNotes) {
    tags.push('准备')
  }

  if (viewModel.isCompleted) {
    tags.push('已完成')
  }

  return tags
}
