import type { AppData } from '@/types'

const createdAt = '2026-07-01T09:00:00.000Z'
const updatedAt = '2026-07-02T13:30:00.000Z'
const today = '2026-07-02'
const selected = '2026-07-05'

export const tutorialDemoAppData: AppData = {
  settings: {
    initialized: true,
    tieBreakerOrder: 'desc',
    weatherEnabled: false,
    completedAtRoundingMinutes: 5,
    defaultNightTodoByTimeEnabled: true,
    defaultNightTodoStartHour: 17,
    defaultNightTodoEndHour: 23,
    createdAt,
    updatedAt,
  },
  sceneTags: [
    {
      id: 'tutorial-scene-evening',
      name: '工作日晚上',
      createdAt,
      updatedAt,
      isBuiltIn: true,
    },
    {
      id: 'tutorial-scene-weekend',
      name: '周末',
      createdAt,
      updatedAt,
      isBuiltIn: true,
    },
    {
      id: 'tutorial-scene-outside',
      name: '出门顺路',
      createdAt,
      updatedAt,
      isBuiltIn: true,
    },
  ],
  activityTypes: [
    {
      id: 'tutorial-activity-reading',
      name: '阅读',
      createdAt,
      updatedAt,
      isBuiltIn: true,
    },
    {
      id: 'tutorial-activity-place',
      name: '探店/地点',
      createdAt,
      updatedAt,
      isBuiltIn: true,
    },
    {
      id: 'tutorial-activity-home',
      name: '家务死角',
      createdAt,
      updatedAt,
      isBuiltIn: true,
    },
  ],
  taskTemplates: [
    {
      id: 'tutorial-template-book',
      templateKind: 'grass',
      title: '读《夜航西飞》',
      date: '',
      activityTypeId: 'tutorial-activity-reading',
      sceneTagIds: ['tutorial-scene-weekend'],
      interestLevel: 3,
      isNecessary: false,
      requiresPreparation: false,
      preparationNotes: '',
      recurrence: 'none',
      repeatType: 'none',
      isSegmented: false,
      isStepped: false,
      currentStep: '',
      nextStep: '',
      createdAt,
      updatedAt,
      grassStatus: 'picked',
      isArchived: false,
    },
    {
      id: 'tutorial-template-garden',
      templateKind: 'grass',
      title: '植物园温室',
      date: '',
      activityTypeId: 'tutorial-activity-place',
      sceneTagIds: ['tutorial-scene-outside'],
      interestLevel: 2,
      isNecessary: false,
      requiresPreparation: false,
      preparationNotes: '',
      recurrence: 'none',
      repeatType: 'none',
      isSegmented: false,
      isStepped: false,
      currentStep: '',
      nextStep: '',
      createdAt,
      updatedAt,
      grassStatus: 'active',
      isArchived: false,
    },
    {
      id: 'tutorial-template-drawer',
      templateKind: 'grass',
      title: '整理厨房抽屉',
      date: '',
      activityTypeId: 'tutorial-activity-home',
      sceneTagIds: ['tutorial-scene-evening'],
      interestLevel: 1,
      isNecessary: false,
      requiresPreparation: false,
      preparationNotes: '',
      recurrence: 'none',
      repeatType: 'none',
      isSegmented: false,
      isStepped: false,
      currentStep: '',
      nextStep: '',
      createdAt,
      updatedAt,
      grassStatus: 'active',
      isArchived: false,
    },
    {
      id: 'tutorial-template-review',
      templateKind: 'todo_recurring',
      title: '周复盘',
      date: selected,
      activityTypeId: 'tutorial-activity-home',
      sceneTagIds: ['tutorial-scene-weekend'],
      interestLevel: 2,
      isNecessary: false,
      requiresPreparation: false,
      preparationNotes: '',
      recurrence: 'weekly',
      repeatType: 'calendar',
      repeatIntervalUnit: 'week',
      repeatIntervalValue: 1,
      isSegmented: false,
      isStepped: false,
      currentStep: '',
      nextStep: '',
      createdAt,
      updatedAt,
      isArchived: false,
    },
  ],
  recurringTaskInstances: [
    {
      id: 'tutorial-recurring-review',
      templateId: 'tutorial-template-review',
      dateKey: selected,
      targetDate: selected,
      recurrence: 'weekly',
      repeatType: 'calendar',
      repeatIntervalUnit: 'week',
      repeatIntervalValue: 1,
      status: 'pending',
      progressState: 'not_started',
      progressPercent: 0,
      progressNote: '',
      generatedAt: createdAt,
      updatedAt,
    },
  ],
  dayPlanItems: [
    {
      id: 'tutorial-todo-necessary',
      date: selected,
      timeBlock: 'day',
      timeBlockSource: 'default_day',
      sortOrder: 1,
      source: 'manual_temporary',
      title: '预约体检',
      activityTypeId: 'tutorial-activity-home',
      isNecessary: true,
      deadlineDate: selected,
      requiresPreparation: true,
      preparationNotes: '先确认医保卡和空腹要求',
      isSegmented: false,
      isStepped: false,
      currentStep: '',
      nextStep: '',
      progressState: 'not_started',
      progressPercent: 0,
      status: 'pending',
      createdAt,
      updatedAt,
    },
    {
      id: 'tutorial-todo-stepped',
      date: selected,
      timeBlock: 'day',
      timeBlockSource: 'default_day',
      sortOrder: 2,
      source: 'decision_selected',
      templateId: 'tutorial-template-book',
      title: '读《夜航西飞》',
      activityTypeId: 'tutorial-activity-reading',
      isNecessary: false,
      requiresPreparation: true,
      preparationNotes: '读完后记录一句喜欢的句子',
      isSegmented: false,
      isStepped: true,
      currentStep: '第一章',
      nextStep: '第二章',
      stepRootItemId: 'tutorial-todo-stepped',
      progressState: 'not_started',
      progressPercent: 0,
      status: 'pending',
      createdAt,
      updatedAt,
    },
    {
      id: 'tutorial-todo-segmented',
      date: selected,
      timeBlock: 'night',
      timeBlockSource: 'manual_night',
      sortOrder: 3,
      source: 'manual_temporary',
      title: '整理旅行资料',
      activityTypeId: 'tutorial-activity-home',
      isNecessary: false,
      requiresPreparation: false,
      preparationNotes: '',
      isSegmented: true,
      isStepped: false,
      currentStep: '',
      nextStep: '',
      progressState: 'in_progress',
      progressPercent: 45,
      status: 'pending',
      createdAt,
      updatedAt,
    },
    {
      id: 'tutorial-todo-recurring',
      date: selected,
      timeBlock: 'night',
      timeBlockSource: 'manual_night',
      sortOrder: 4,
      source: 'auto_generated',
      templateId: 'tutorial-template-review',
      recurringInstanceId: 'tutorial-recurring-review',
      title: '周复盘',
      activityTypeId: 'tutorial-activity-home',
      isNecessary: false,
      requiresPreparation: false,
      preparationNotes: '',
      isSegmented: false,
      isStepped: false,
      currentStep: '',
      nextStep: '',
      progressState: 'not_started',
      progressPercent: 0,
      status: 'pending',
      createdAt,
      updatedAt,
    },
    {
      id: 'tutorial-todo-completed',
      date: selected,
      timeBlock: 'day',
      timeBlockSource: 'default_day',
      sortOrder: 5,
      source: 'decision_selected',
      templateId: 'tutorial-template-garden',
      title: '确认植物园开放时间',
      activityTypeId: 'tutorial-activity-place',
      isNecessary: false,
      requiresPreparation: false,
      preparationNotes: '',
      isSegmented: false,
      isStepped: false,
      currentStep: '',
      nextStep: '',
      progressState: 'completed',
      progressPercent: 100,
      status: 'completed',
      completedAt: '2026-07-05T10:30:00.000Z',
      createdAt,
      updatedAt,
    },
    {
      id: 'tutorial-todo-today',
      date: today,
      timeBlock: 'day',
      timeBlockSource: 'default_day',
      sortOrder: 1,
      source: 'manual_temporary',
      title: '今天页面示例事项',
      activityTypeId: 'tutorial-activity-home',
      isNecessary: false,
      requiresPreparation: false,
      preparationNotes: '',
      isSegmented: false,
      isStepped: false,
      currentStep: '',
      nextStep: '',
      progressState: 'not_started',
      progressPercent: 0,
      status: 'pending',
      createdAt,
      updatedAt,
    },
  ],
  logbookEntries: [
    {
      date: selected,
      generatedAt: '2026-07-05T23:50:00.000Z',
      remark: '教学演示：日志会把完成、未完成和删除过的事项收进当天快照。',
      snapshotItems: [
        {
          id: 'tutorial-log-completed',
          status: 'completed',
          titleSnapshot: '确认植物园开放时间',
          time: '10:30',
          isNecessary: false,
          isPicked: true,
          isSegmented: false,
          deadlineStatus: 'none',
        },
        {
          id: 'tutorial-log-pending',
          status: 'pending',
          titleSnapshot: '读《夜航西飞》：第一章',
          isNecessary: false,
          isPicked: true,
          isSegmented: false,
          deadlineStatus: 'none',
        },
        {
          id: 'tutorial-log-necessary',
          status: 'pending',
          titleSnapshot: '预约体检',
          isNecessary: true,
          isPicked: false,
          isSegmented: false,
          deadlineDate: selected,
          deadlineStatus: 'normal',
        },
      ],
    },
  ],
  segmentedProgressLogs: [
    {
      date: selected,
      itemId: 'tutorial-todo-segmented',
      titleSnapshot: '整理旅行资料',
      isNecessary: false,
      fromProgress: 20,
      toProgress: 45,
    },
  ],
}
